import type { Locale } from './i18n'

type LocalizedText = {
  es: string
  en: string
}

export type VictimSceneNote = {
  date: string
  victim: LocalizedText
  location: LocalizedText
  scene: LocalizedText
  investigation: LocalizedText
}

const t = (es: string, en: string): LocalizedText => ({ es, en })

const notes: Record<string, VictimSceneNote[]> = {
  zodiac: [
    { date: '20 dic 1968', victim: t('David Faraday y Betty Lou Jensen', 'David Faraday and Betty Lou Jensen'), location: t('Lake Herman Road, cerca de Vallejo', 'Lake Herman Road, near Vallejo'), scene: t('Pareja joven atacada junto al coche en una carretera aislada. Faraday fue disparado a corta distancia; Jensen fue alcanzada al intentar huir.', 'Young couple attacked beside their car on an isolated road. Faraday was shot at close range; Jensen was hit while trying to flee.'), investigation: t('Escena rural, sin testigo directo del disparo. El caso quedo unido al patron Zodiac cuando llegaron cartas y llamadas posteriores.', 'Rural scene, no direct shooting witness. The case became tied to Zodiac through later letters and calls.') },
    { date: '4 jul 1969', victim: t('Darlene Ferrin y Michael Mageau', 'Darlene Ferrin and Michael Mageau'), location: t('Blue Rock Springs Park, Vallejo', 'Blue Rock Springs Park, Vallejo'), scene: t('Ataque con arma de fuego contra una pareja dentro de un coche aparcado. Ferrin murio; Mageau sobrevivio y aporto descripcion.', 'Gun attack against a couple in a parked car. Ferrin died; Mageau survived and gave a description.'), investigation: t('Una llamada a la policia reclamo este ataque y el de Lake Herman Road.', 'A call to police claimed this attack and the Lake Herman Road murders.') },
    { date: '27 sep 1969', victim: t('Cecelia Shepard y Bryan Hartnell', 'Cecelia Shepard and Bryan Hartnell'), location: t('Lake Berryessa, Napa County', 'Lake Berryessa, Napa County'), scene: t('El agresor aparecio encapuchado, ato a la pareja y la apunalo. Dejo escritura en la puerta del coche.', 'The attacker appeared hooded, tied the couple, and stabbed them. He left writing on the car door.'), investigation: t('Hartnell sobrevivio; la puerta del coche y la llamada posterior son piezas clave.', 'Hartnell survived; the car-door writing and later call are key items.') },
    { date: '11 oct 1969', victim: t('Paul Stine', 'Paul Stine'), location: t('Presidio Heights, San Francisco', 'Presidio Heights, San Francisco'), scene: t('Taxista asesinado en un entorno urbano. El agresor tomo parte de la camisa de la victima.', 'Cab driver killed in an urban setting. The attacker took part of the victim shirt.'), investigation: t('Testigos permitieron un retrato robot; fragmentos de camisa llegaron con cartas.', 'Witnesses enabled a composite sketch; shirt fragments arrived with letters.') },
  ],
  'jack-the-ripper': [
    { date: '31 ago 1888', victim: t('Mary Ann Nichols', 'Mary Ann Nichols'), location: t('Buck’s Row, Whitechapel', 'Buck’s Row, Whitechapel'), scene: t('Cuerpo hallado en la via publica con cortes en garganta y abdomen.', 'Body found in the street with throat and abdominal wounds.'), investigation: t('La rapidez del ataque y la exposicion publica marcaron el inicio canonico.', 'The speed of the attack and public exposure marked the canonical beginning.') },
    { date: '8 sep 1888', victim: t('Annie Chapman', 'Annie Chapman'), location: t('Hanbury Street', 'Hanbury Street'), scene: t('Hallada en patio trasero; mutilaciones mas extensas que en Nichols.', 'Found in a backyard; mutilations more extensive than Nichols.'), investigation: t('La escena sugirio conocimiento anatomico discutido y aumento de vigilancia.', 'The scene suggested debated anatomical knowledge and increased patrols.') },
    { date: '30 sep 1888', victim: t('Elizabeth Stride', 'Elizabeth Stride'), location: t('Dutfield’s Yard', 'Dutfield’s Yard'), scene: t('Degollada sin mutilacion abdominal confirmada; posible interrupcion del agresor.', 'Throat cut without confirmed abdominal mutilation; possible interruption of the attacker.'), investigation: t('Forma parte del llamado doble suceso junto a Eddowes.', 'Part of the so-called double event with Eddowes.') },
    { date: '30 sep 1888', victim: t('Catherine Eddowes', 'Catherine Eddowes'), location: t('Mitre Square', 'Mitre Square'), scene: t('Mutilaciones graves en una plaza patrullada minutos antes.', 'Severe mutilations in a square patrolled minutes earlier.'), investigation: t('El delantal hallado en Goulston Street y el grafito asociado generaron controversia.', 'The apron found in Goulston Street and associated graffiti generated controversy.') },
    { date: '9 nov 1888', victim: t('Mary Jane Kelly', 'Mary Jane Kelly'), location: t('Miller’s Court', 'Miller’s Court'), scene: t('Unica escena canonica en interior privado, con violencia extrema y tiempo prolongado.', 'Only canonical private indoor scene, with extreme violence and extended time.'), investigation: t('La fotografia de escena se convirtio en uno de los documentos visuales mas citados del caso.', 'The crime-scene photograph became one of the case most cited visual documents.') },
  ],
  'cleveland-torso': [
    { date: 'sep 1935', victim: t('Edward Andrassy y hombre no identificado', 'Edward Andrassy and unidentified man'), location: t('Jackass Hill, Kingsbury Run', 'Jackass Hill, Kingsbury Run'), scene: t('Cuerpos decapitados y emasculados encontrados cerca del cauce ferroviario.', 'Decapitated and emasculated bodies found near the rail ravine.'), investigation: t('Andrassy fue identificado por huellas; el segundo hombre no.', 'Andrassy was identified by fingerprints; the second man was not.') },
    { date: 'ene 1936', victim: t('Florence Polillo', 'Florence Polillo'), location: t('Central Avenue y Orange Avenue', 'Central Avenue and Orange Avenue'), scene: t('Restos envueltos en periodico y depositados en cestas y solares.', 'Remains wrapped in newspaper and deposited in baskets and vacant lots.'), investigation: t('Identificada por huellas; Frank Dolezal fue acusado despues, de forma muy cuestionada.', 'Identified by fingerprints; Frank Dolezal was later accused, very controversially.') },
    { date: 'jun 1936', victim: t('El hombre tatuado', 'The Tattooed Man'), location: t('East 55th Street bridge', 'East 55th Street bridge'), scene: t('Cabeza y cuerpo recuperados por separado; seis tatuajes usados para intentar identificarlo.', 'Head and body recovered separately; six tattoos used in identification efforts.'), investigation: t('Mascara mortuoria y tabla de tatuajes fueron expuestas al publico.', 'Death mask and tattoo chart were displayed to the public.') },
    { date: 'ago 1938', victim: t('Victimas 11 y 12', 'Victims 11 and 12'), location: t('East 9th y Lakeside', 'East 9th and Lakeside'), scene: t('Restos depositados cerca de una zona visible desde oficinas de Eliot Ness.', 'Remains deposited near an area visible from Eliot Ness office.'), investigation: t('Provoco la redada y quema de asentamientos de Kingsbury Run.', 'Triggered the raid and burning of Kingsbury Run shantytowns.') },
  ],
  'servant-girl-annihilator': [
    { date: '30 dic 1884', victim: t('Mollie Smith', 'Mollie Smith'), location: t('Austin, cerca de la casa donde trabajaba', 'Austin, near the home where she worked'), scene: t('Cocinera negra atacada de noche con hacha y cuchillo.', 'Black cook attacked at night with axe and knife.'), investigation: t('Primer caso que fija el miedo a intrusiones nocturnas.', 'First case that fixed fear of night intrusions.') },
    { date: '7 may 1885', victim: t('Eliza Shelley', 'Eliza Shelley'), location: t('Austin', 'Austin'), scene: t('Ataque con hacha dentro del patron inicial contra sirvientas.', 'Axe attack within the early pattern against servant women.'), investigation: t('Confirmo que no se trataba de una violencia aislada.', 'Confirmed the violence was not isolated.') },
    { date: '30 ago 1885', victim: t('Mary Ramey', 'Mary Ramey'), location: t('Lavadero/washhouse', 'Washhouse'), scene: t('Nina de 11 anos arrastrada y asesinada.', 'Eleven-year-old girl dragged away and murdered.'), investigation: t('El caso amplio desborda la etiqueta de “servant girls”.', 'The wider case exceeds the “servant girls” label.') },
    { date: '24 dic 1885', victim: t('Susan Hancock y Eula Phillips', 'Susan Hancock and Eula Phillips'), location: t('Dos domicilios de Austin', 'Two Austin homes'), scene: t('Dos ataques separados en Nochebuena contra mujeres blancas.', 'Two separate Christmas Eve attacks against white women.'), investigation: t('La ciudad entro en panico; la serie ceso despues sin resolucion judicial.', 'The city entered panic; the series then stopped without judicial resolution.') },
  ],
  'freeway-phantom': [
    { date: '25 abr 1971', victim: t('Carol Spinks', 'Carol Spinks'), location: t('Washington, D.C. / I-295', 'Washington, D.C. / I-295'), scene: t('Nina secuestrada y hallada junto a via rapida.', 'Girl abducted and found near a freeway.'), investigation: t('Primera victima reconocida por MPDC.', 'First victim recognized by MPDC.') },
    { date: 'jul 1971', victim: t('Darrelenia Johnson y Brenda Crockett', 'Darrelenia Johnson and Brenda Crockett'), location: t('D.C. y Prince George’s County', 'D.C. and Prince George’s County'), scene: t('Cuerpos abandonados cerca de carreteras; Crockett hizo llamadas antes de aparecer muerta.', 'Bodies left near roads; Crockett made calls before being found dead.'), investigation: t('Las llamadas sugieren cautiverio breve y control del agresor.', 'The calls suggest brief captivity and offender control.') },
    { date: 'oct-nov 1971', victim: t('Nenomoshia Yates y Brenda Woodard', 'Nenomoshia Yates and Brenda Woodard'), location: t('Benning Road / Baltimore-Washington Parkway', 'Benning Road / Baltimore-Washington Parkway'), scene: t('Victimas estranguladas; en Woodard aparece la nota “Free-way Phantom”.', 'Victims strangled; Woodard is found with the “Free-way Phantom” note.'), investigation: t('La nota transforma el caso en comunicacion directa con policia y prensa.', 'The note turns the case into direct communication with police and press.') },
    { date: '5 sep 1972', victim: t('Diane Williams', 'Diane Williams'), location: t('I-295', 'I-295'), scene: t('Ultima victima reconocida, hallada horas despues de ser vista viva.', 'Last recognized victim, found hours after last being seen alive.'), investigation: t('El expediente sigue abierto y afectado por perdida de evidencia fisica.', 'The file remains open and affected by lost physical evidence.') },
  ],
  'the-doodler': [
    { date: '1974', victim: t('Gerald Cavanagh, Joseph Stevens, Klaus Christmann', 'Gerald Cavanagh, Joseph Stevens, Klaus Christmann'), location: t('Ocean Beach y costa de San Francisco', 'Ocean Beach and San Francisco coast'), scene: t('Hombres gays encontrados muertos en zonas costeras o parques.', 'Gay men found dead in coastal or park areas.'), investigation: t('El patron combina bares, aislamiento y violencia dirigida a hombres gays.', 'The pattern combines bars, isolation, and violence against gay men.') },
    { date: '1975', victim: t('Frederick Capin y Harald Gullberg', 'Frederick Capin and Harald Gullberg'), location: t('Ocean Beach / Golden Gate Park', 'Ocean Beach / Golden Gate Park'), scene: t('Nuevos cuerpos sostienen la hipotesis de serie.', 'Further bodies support the serial hypothesis.'), investigation: t('Supervivientes describen a un hombre que dibujaba para aproximarse.', 'Survivors describe a man who drew sketches to approach victims.') },
    { date: '1976', victim: t('Supervivientes no identificados publicamente', 'Survivors not publicly identified'), location: t('San Francisco', 'San Francisco'), scene: t('Ataques sobrevividos generan retrato forense.', 'Survived attacks generate a forensic sketch.'), investigation: t('Un sospechoso fue detenido, pero no acusado.', 'A suspect was detained but not charged.') },
  ],
  'texarkana-phantom': [
    { date: '22 feb 1946', victim: t('Jimmy Hollis y Mary Jeanne Larey', 'Jimmy Hollis and Mary Jeanne Larey'), location: t('Texarkana', 'Texarkana'), scene: t('Primer ataque sobrevivido contra una pareja aparcada.', 'First survived attack against a parked couple.'), investigation: t('La descripcion inicial fue imprecisa, pero marco el inicio del miedo publico.', 'The initial description was imprecise but marked the beginning of public fear.') },
    { date: '24 mar 1946', victim: t('Richard Griffin y Polly Ann Moore', 'Richard Griffin and Polly Ann Moore'), location: t('Camino rural', 'Rural road'), scene: t('Pareja asesinada a tiros en un coche.', 'Couple shot dead in a car.'), investigation: t('La serie se consolida como ataque a parejas aisladas.', 'The series consolidates as attacks on isolated couples.') },
    { date: '14 abr 1946', victim: t('Paul Martin y Betty Jo Booker', 'Paul Martin and Betty Jo Booker'), location: t('Spring Lake Park area', 'Spring Lake Park area'), scene: t('Ambos aparecen muertos tras una noche de musica y desplazamientos.', 'Both are found dead after a night of music and travel.'), investigation: t('La ciudad inicia patrullas masivas y medidas de autoproteccion.', 'The city begins mass patrols and self-protection measures.') },
    { date: '3 may 1946', victim: t('Virgil y Katie Starks', 'Virgil and Katie Starks'), location: t('Domicilio Starks', 'Starks home'), scene: t('Ataque a traves de una ventana; Virgil muere y Katie sobrevive.', 'Attack through a window; Virgil dies and Katie survives.'), investigation: t('Rompe el patron de parejas aparcadas y aumenta la incertidumbre.', 'Breaks the parked-couple pattern and increases uncertainty.') },
  ],
  'west-mesa': [
    { date: '2001-2005', victim: t('Once mujeres y un feto', 'Eleven women and one fetal victim'), location: t('Albuquerque, New Mexico', 'Albuquerque, New Mexico'), scene: t('Mujeres desaparecidas en contextos de calle, movilidad o trabajo sexual.', 'Women disappear amid street life, mobility, or sex-work contexts.'), investigation: t('Varias desapariciones no fueron leidas al principio como una sola serie.', 'Several disappearances were not initially read as one series.') },
    { date: 'feb 2009', victim: t('Jamie Barela, Evelyn Salazar, Cinnamon Elks y otras victimas identificadas', 'Jamie Barela, Evelyn Salazar, Cinnamon Elks and other identified victims'), location: t('118th Street SW, West Mesa', '118th Street SW, West Mesa'), scene: t('Restos humanos localizados en una zona de expansion urbana.', 'Human remains located in an area of urban expansion.'), investigation: t('La excavacion revela una fosa clandestina con multiples victimas.', 'The excavation reveals a clandestine grave with multiple victims.') },
    { date: '2009+', victim: t('Victimas relacionadas posibles', 'Possible related victims'), location: t('Albuquerque y alrededores', 'Albuquerque and surrounding areas'), scene: t('Otras mujeres desaparecidas se revisan por posible relacion.', 'Other missing women are reviewed for possible connection.'), investigation: t('APD mantiene task force y recompensas; no hay acusado.', 'APD maintains task force and rewards; no one is charged.') },
  ],
  'bible-john': [
    { date: '1968', victim: t('Patricia Docker', 'Patricia Docker'), location: t('Glasgow', 'Glasgow'), scene: t('Encontrada muerta tras salir de ambiente nocturno.', 'Found dead after leaving nightlife.'), investigation: t('Primer caso que despues se agrupa con Barrowland.', 'First case later grouped with Barrowland.') },
    { date: '1969', victim: t('Jemima MacDonald', 'Jemima MacDonald'), location: t('Glasgow', 'Glasgow'), scene: t('Hallada asesinada tras una noche de baile.', 'Found murdered after a night out dancing.'), investigation: t('Refuerza el patron de victimas que salen de locales de baile.', 'Reinforces the pattern of victims leaving dance halls.') },
    { date: '31 oct 1969', victim: t('Helen Puttock', 'Helen Puttock'), location: t('Earl Street, Glasgow', 'Earl Street, Glasgow'), scene: t('Aparece muerta tras compartir taxi con su hermana y un hombre desconocido.', 'Found dead after sharing a taxi with her sister and an unknown man.'), investigation: t('El testimonio de Jean Langford da la descripcion mas citada de Bible John.', 'Jean Langford testimony gives the most cited Bible John description.') },
  ],
  'monster-of-florence': [
    { date: '1968-1985', victim: t('Ocho parejas', 'Eight couples'), location: t('Campos y caminos de Toscana', 'Tuscan fields and rural roads'), scene: t('Parejas atacadas en coches o espacios apartados; arma .22 Beretta vinculada.', 'Couples attacked in cars or secluded spaces; .22 Beretta weapon linked.'), investigation: t('La continuidad balistica es una de las columnas del expediente.', 'Ballistic continuity is one of the file pillars.') },
    { date: '1981-1985', victim: t('Victimas con mutilaciones', 'Victims with mutilations'), location: t('Scandicci, Baccaiano, Giogoli, Vicchio, Scopeti', 'Scandicci, Baccaiano, Giogoli, Vicchio, Scopeti'), scene: t('Algunos ataques incluyen mutilaciones post mortem.', 'Some attacks include post-mortem mutilations.'), investigation: t('Estas escenas abren teorias de ritual, trofeo o mercado criminal, todas controvertidas.', 'These scenes open ritual, trophy, or criminal-market theories, all controversial.') },
    { date: '1990s+', victim: t('Expediente judicial complejo', 'Complex judicial file'), location: t('Florencia y Perugia', 'Florence and Perugia'), scene: t('La escena judicial se vuelve casi tan importante como las escenas de crimen.', 'The judicial scene becomes almost as important as the crime scenes.'), investigation: t('Condenas, absoluciones y teorias multiples no eliminan la duda publica.', 'Convictions, acquittals, and multiple theories do not remove public doubt.') },
  ],
  'eastbound-strangler': [
    { date: '20 nov 2006', victim: t('Kim Raffo, Barbara Breidor, Molly Dilts y Tracy Ann Roberts', 'Kim Raffo, Barbara Breidor, Molly Dilts, and Tracy Ann Roberts'), location: t('Zanja tras Golden Key Motel, Egg Harbor Township', 'Drainage ditch behind Golden Key Motel, Egg Harbor Township'), scene: t('Cuatro cuerpos hallados alineados, boca abajo, cerca de Black Horse Pike.', 'Four bodies found aligned, face-down, near Black Horse Pike.'), investigation: t('La disposicion conjunta sugiere control de escena y posible autor serial.', 'The joint arrangement suggests scene control and possible serial authorship.') },
    { date: '2006+', victim: t('Mujeres en contexto de explotacion y calle', 'Women in exploitation and street contexts'), location: t('Atlantic City', 'Atlantic City'), scene: t('Victimas vinculadas a entornos de alta vulnerabilidad.', 'Victims linked to high-vulnerability environments.'), investigation: t('Comparaciones con otros asesinos no produjeron identificacion definitiva.', 'Comparisons with other killers did not produce a definitive identification.') },
  ],
  'jeff-davis-8': [
    { date: '2005-2009', victim: t('Ocho mujeres de Jefferson Davis Parish', 'Eight women from Jefferson Davis Parish'), location: t('Jennings y canales/caminos rurales', 'Jennings and rural canals/roads'), scene: t('Cuerpos encontrados en canales, carreteras o zonas rurales.', 'Bodies found in canals, roads, or rural areas.'), investigation: t('Las victimas se conocian entre si o compartian redes, lo que complica una lectura simple.', 'The victims knew each other or shared networks, complicating a simple reading.') },
    { date: 'Durante la investigacion', victim: t('Informantes y testigos', 'Informants and witnesses'), location: t('Jefferson Davis Parish', 'Jefferson Davis Parish'), scene: t('El expediente se mezcla con drogas, trabajo sexual, rumores policiales y miedo local.', 'The file mixes drugs, sex work, police rumors, and local fear.'), investigation: t('La teoria de asesino unico convive con hipotesis de encubrimiento o crimen organizado.', 'The single-killer theory coexists with cover-up or organized-crime hypotheses.') },
  ],
  'chicago-strangler': [
    { date: '2001+', victim: t('Mujeres estranguladas o asfixiadas en Chicago', 'Women strangled or asphyxiated in Chicago'), location: t('Chicago, multiples barrios', 'Chicago, multiple neighborhoods'), scene: t('Casos dispersos con metodo semejante, a menudo en zonas de abandono o interior.', 'Dispersed cases with similar method, often in abandoned areas or indoors.'), investigation: t('El patron es estadistico y periodistico; no todos los casos estan oficialmente unidos.', 'The pattern is statistical and journalistic; not all cases are officially linked.') },
    { date: '2010s+', victim: t('Victimas negras y vulnerables', 'Black and vulnerable victims'), location: t('South y West Side, entre otras zonas', 'South and West Side, among other areas'), scene: t('Muchos expedientes muestran desigualdad de atencion publica.', 'Many files show unequal public attention.'), investigation: t('El valor profesional esta en separar datos de una narrativa unica no probada.', 'The professional value lies in separating data from an unproved single narrative.') },
  ],
  'chillicothe-six': [
    { date: '2014-2015', victim: t('Charlotte Trego, Wanda Lemons, Tameka Lynch, Shasta Himelrick, Timberly Claytor y Tiffany Sayre', 'Charlotte Trego, Wanda Lemons, Tameka Lynch, Shasta Himelrick, Timberly Claytor, and Tiffany Sayre'), location: t('Chillicothe y Ross County, Ohio', 'Chillicothe and Ross County, Ohio'), scene: t('Desapariciones y muertes en un circulo pequeno de mujeres vulnerables.', 'Disappearances and deaths within a small circle of vulnerable women.'), investigation: t('No todas comparten el mismo estado procesal; algunas lineas fueron resueltas por separado.', 'Not all share the same procedural status; some lines were resolved separately.') },
    { date: '2015+', victim: t('Familias y comunidad', 'Families and community'), location: t('Ross County', 'Ross County'), scene: t('La escena social incluye adiccion, pobreza, violencia y miedo a hablar.', 'The social scene includes addiction, poverty, violence, and fear of speaking.'), investigation: t('El enfoque profesional exige distinguir patron mediatico, coincidencias y pruebas.', 'A professional approach must distinguish media pattern, coincidences, and evidence.') },
  ],
  'gilgo-beach-unresolved': [
    { date: '2010-2011', victim: t('Gilgo Four y otros restos de Ocean Parkway', 'Gilgo Four and other Ocean Parkway remains'), location: t('Long Island, Nueva York', 'Long Island, New York'), scene: t('Restos localizados durante la busqueda de Shannan Gilbert.', 'Remains located during the search for Shannan Gilbert.'), investigation: t('La investigacion separa victimas acusadas/admitidas de restos aun debatidos.', 'The investigation separates charged/admitted victims from still-debated remains.') },
    { date: '2023+', victim: t('Victimas vinculadas al proceso Heuermann', 'Victims linked to the Heuermann case'), location: t('Suffolk County', 'Suffolk County'), scene: t('Telefonia, ADN, objetos y movimientos se vuelven piezas centrales.', 'Phone data, DNA, objects, and movements become central pieces.'), investigation: t('El caso amplio ya no puede describirse como totalmente anonimo, pero tampoco como completamente cerrado.', 'The wider case can no longer be described as fully anonymous, but not fully closed either.') },
  ],
}

export function getVictimSceneNotes(slug: string) {
  return notes[slug] ?? []
}

export function localizeVictimScene(note: VictimSceneNote, locale: Locale) {
  return {
    date: note.date,
    victim: note.victim[locale],
    location: note.location[locale],
    scene: note.scene[locale],
    investigation: note.investigation[locale],
  }
}
