import type { Locale } from './i18n'

type LocalizedText = {
  es: string
  en: string
}

export type CaseMapPoint = {
  slug: string
  date: string
  title: LocalizedText
  category: 'scene' | 'last-seen' | 'body-recovery' | 'suspect-lead' | 'context'
  location: LocalizedText
  latitude: number
  longitude: number
  precision: LocalizedText
  note: LocalizedText
  sourceLabel: string
  sourceUrl: string
}

const t = (es: string, en: string): LocalizedText => ({ es, en })

const points: CaseMapPoint[] = [
  {
    slug: 'cleveland-torso',
    date: 'sep 1935',
    title: t('Jackass Hill / Kingsbury Run', 'Jackass Hill / Kingsbury Run'),
    category: 'scene',
    location: t('Kingsbury Run, Cleveland', 'Kingsbury Run, Cleveland'),
    latitude: 41.48694,
    longitude: -81.66,
    precision: t('Coordenada publica aproximada del corredor de Kingsbury Run.', 'Approximate public coordinate for the Kingsbury Run corridor.'),
    note: t('Zona asociada al hallazgo de Edward Andrassy y un segundo hombre no identificado.', 'Area associated with the discovery of Edward Andrassy and a second unidentified man.'),
    sourceLabel: 'Cleveland Police Museum / Project Unredacted coordinate cross-check',
    sourceUrl: 'https://www.clevelandpolicemuseum.org/collections/torso-murders/',
  },
  {
    slug: 'cleveland-torso',
    date: 'ene 1936',
    title: t('Central Avenue y Orange Avenue', 'Central Avenue and Orange Avenue'),
    category: 'body-recovery',
    location: t('Cleveland, Ohio', 'Cleveland, Ohio'),
    latitude: 41.496,
    longitude: -81.683,
    precision: t('Interseccion aproximada citada en relatos publicos.', 'Approximate intersection cited in public accounts.'),
    note: t('Restos de Florence Polillo fueron vinculados publicamente a esta zona.', 'Florence Polillo remains were publicly linked to this area.'),
    sourceLabel: 'Encyclopedia of Cleveland History: Torso Murders',
    sourceUrl: 'https://case.edu/ech/articles/t/torso-murders',
  },
  {
    slug: 'cleveland-torso',
    date: 'jun 1936',
    title: t('Puente de East 55th Street', 'East 55th Street bridge'),
    category: 'body-recovery',
    location: t('East 55th Street, Cleveland', 'East 55th Street, Cleveland'),
    latitude: 41.486,
    longitude: -81.651,
    precision: t('Punto aproximado del puente/corredor citado.', 'Approximate bridge/corridor point.'),
    note: t('Zona asociada al hallazgo del llamado hombre tatuado.', 'Area associated with the Tattooed Man recovery.'),
    sourceLabel: 'Cleveland Police Museum: Identifying the Victims',
    sourceUrl: 'https://www.clevelandpolicemuseum.org/torso-murders/torso-murders-identifying-the-victims/',
  },
  {
    slug: 'cleveland-torso',
    date: 'ago 1938',
    title: t('East 9th y Lakeside', 'East 9th and Lakeside'),
    category: 'body-recovery',
    location: t('Downtown Cleveland', 'Downtown Cleveland'),
    latitude: 41.5067,
    longitude: -81.6906,
    precision: t('Interseccion urbana aproximada.', 'Approximate urban intersection.'),
    note: t('Restos de las victimas 11 y 12 aparecieron cerca de una zona visible desde oficinas de Eliot Ness.', 'Victims 11 and 12 were found near an area publicly tied to Eliot Ness office visibility.'),
    sourceLabel: 'Cleveland Police Museum: Torso Murders',
    sourceUrl: 'https://www.clevelandpolicemuseum.org/collections/torso-murders/',
  },
  {
    slug: 'freeway-phantom',
    date: 'jul 1971',
    title: t('Carol Spinks y Darlenia Johnson - I-295', 'Carol Spinks and Darlenia Johnson - I-295'),
    category: 'body-recovery',
    location: t('I-295, frontera D.C./Maryland', 'I-295, D.C./Maryland border'),
    latitude: 38.816,
    longitude: -76.996,
    precision: t('Punto aproximado por carretera; la fuente publica describe zona y distancia.', 'Approximate roadway point; public source describes area and distance.'),
    note: t('Cuerpos hallados en la zona de autopista que da nombre al caso.', 'Bodies found in the freeway area that gave the case its name.'),
    sourceLabel: 'Freeway Phantom victim map',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '27 jul 1971',
    title: t('Brenda Crockett - casa', 'Brenda Crockett - home'),
    category: 'last-seen',
    location: t('2414 12th Place NW, Washington D.C.', '2414 12th Place NW, Washington, D.C.'),
    latitude: 38.921,
    longitude: -77.028,
    precision: t('Direccion publica aproximada al bloque.', 'Public address approximated to block level.'),
    note: t('La fuente publica la ubica saliendo hacia una tienda Safeway a pocas manzanas.', 'Public source places her leaving for a nearby Safeway.'),
    sourceLabel: 'Freeway Phantom victim map',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '28 jul 1971',
    title: t('Brenda Crockett - Route 50 / Cheverly', 'Brenda Crockett - Route 50 / Cheverly'),
    category: 'body-recovery',
    location: t('John Hanson Highway, cerca de Cheverly', 'John Hanson Highway, near Cheverly'),
    latitude: 38.925,
    longitude: -76.916,
    precision: t('Punto aproximado por descripcion de carretera.', 'Approximate point from roadway description.'),
    note: t('Cuerpo hallado junto a US Route 50 cerca de Baltimore-Washington Parkway.', 'Body found along US Route 50 near the Baltimore-Washington Parkway.'),
    sourceLabel: 'Freeway Phantom victim map',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '1 oct 1971',
    title: t('Nenomoshia Yates - Safeway Benning Road', 'Nenomoshia Yates - Benning Road Safeway'),
    category: 'last-seen',
    location: t('4801 Benning Road SE, Washington D.C.', '4801 Benning Road SE, Washington, D.C.'),
    latitude: 38.883,
    longitude: -76.936,
    precision: t('Direccion publica aproximada.', 'Approximate public address.'),
    note: t('Ultima vista saliendo de Safeway; las compras quedaron dispersas en el aparcamiento.', 'Last seen leaving Safeway; groceries were reportedly scattered in the parking lot.'),
    sourceLabel: 'Freeway Phantom victim map',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '1 oct 1971',
    title: t('Nenomoshia Yates - Pennsylvania Avenue', 'Nenomoshia Yates - Pennsylvania Avenue'),
    category: 'body-recovery',
    location: t('Pennsylvania Avenue, Prince George County', 'Pennsylvania Avenue, Prince George County'),
    latitude: 38.869,
    longitude: -76.944,
    precision: t('Punto aproximado cerca de Cedar Hill Cemetery.', 'Approximate point near Cedar Hill Cemetery.'),
    note: t('Hallazgo descrito justo cruzando la linea de D.C.', 'Recovery described just over the D.C. line.'),
    sourceLabel: 'Freeway Phantom victim map',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '15-16 nov 1971',
    title: t('Brenda Woodard - Cardozo / Ben\'s Chili Bowl / ruta', 'Brenda Woodard - Cardozo / Ben\'s Chili Bowl / route'),
    category: 'last-seen',
    location: t('1200 Clifton Road NW y 1213 U Street NW', '1200 Clifton Road NW and 1213 U Street NW'),
    latitude: 38.917,
    longitude: -77.028,
    precision: t('Punto central aproximado entre ubicaciones publicas citadas.', 'Approximate center point between cited public locations.'),
    note: t('La ruta publica incluye Cardozo High School, Ben\'s Chili Bowl y un transbordo hacia casa.', 'Public route includes Cardozo High School, Ben\'s Chili Bowl, and a bus transfer toward home.'),
    sourceLabel: 'Washington Post archive / Freeway Phantom victim map',
    sourceUrl: 'https://www.washingtonpost.com/archive/politics/2006/06/26/freeway-phantom-slayings-haunt-police-families-span-classbankheadsix-young-dc-females-vanished-in-the-70sspan/08789f47-3d0e-4a88-ad24-cdbcc493698f/',
  },
  {
    slug: 'freeway-phantom',
    date: '16 nov 1971',
    title: t('Brenda Woodard - Kenilworth / Route 50', 'Brenda Woodard - Kenilworth / Route 50'),
    category: 'body-recovery',
    location: t('Kenilworth Avenue y Route 50', 'Kenilworth Avenue and Route 50'),
    latitude: 38.913,
    longitude: -76.944,
    precision: t('Interseccion aproximada citada por fuentes publicas.', 'Approximate intersection cited by public sources.'),
    note: t('Lugar publico asociado al hallazgo y a la nota Free-way Phantom.', 'Publicly associated recovery area and Free-way Phantom note.'),
    sourceLabel: 'Freeway Phantom victim map / Washington Post archive',
    sourceUrl: 'https://freeway-phantom.com/victim-map/',
  },
  {
    slug: 'freeway-phantom',
    date: '6 sep 1972',
    title: t('Diane Williams - Route 295', 'Diane Williams - Route 295'),
    category: 'body-recovery',
    location: t('Route 295, Prince George County', 'Route 295, Prince George County'),
    latitude: 38.817,
    longitude: -76.995,
    precision: t('Punto aproximado; Maryland State Police cita un cuarto de milla al norte de la linea D.C./Maryland.', 'Approximate point; Maryland State Police cites a quarter mile north of the D.C./Maryland line.'),
    note: t('Cuerpo identificado como Diane Williams; causa publicada: estrangulamiento.', 'Body identified as Diane Williams; published cause: strangulation.'),
    sourceLabel: 'Maryland State Police cold case: Diane Williams',
    sourceUrl: 'https://mdsp.maryland.gov/Organization/Pages/CriminalInvestigationBureau/CriminalEnforcementDivision/ColdCasesResults.aspx?CCID=55',
  },
  {
    slug: 'the-doodler',
    date: '27 ene 1974',
    title: t('Gerald Cavanagh - Ocean Beach / Ulloa', 'Gerald Cavanagh - Ocean Beach / Ulloa'),
    category: 'body-recovery',
    location: t('Ocean Beach, frente a Ulloa Street', 'Ocean Beach, across from Ulloa Street'),
    latitude: 37.7409,
    longitude: -122.5065,
    precision: t('Punto aproximado; SFPD y Chronicle citan Ocean Beach y Ulloa.', 'Approximate point; SFPD and Chronicle cite Ocean Beach and Ulloa.'),
    note: t('La llamada anonima de 1974 informo de un cuerpo en la playa.', 'The anonymous 1974 call reported a body on the beach.'),
    sourceLabel: 'SFPD Doodler update / San Francisco Chronicle',
    sourceUrl: 'https://www.sanfranciscopolice.org/news/sfpd-provides-update-doodler-cold-case-investigation-19-014',
  },
  {
    slug: 'the-doodler',
    date: '25 jun 1974',
    title: t('Joseph "Jae" Stevens - Spreckels Lake', 'Joseph "Jae" Stevens - Spreckels Lake'),
    category: 'body-recovery',
    location: t('Spreckels Lake, Golden Gate Park', 'Spreckels Lake, Golden Gate Park'),
    latitude: 37.7709,
    longitude: -122.4845,
    precision: t('Punto aproximado en el lago citado por Chronicle.', 'Approximate point at the lake cited by the Chronicle.'),
    note: t('Lugar publico asociado al hallazgo de Joseph Stevens.', 'Publicly associated recovery area for Joseph Stevens.'),
    sourceLabel: 'San Francisco Chronicle Doodler project',
    sourceUrl: 'https://www.sfchronicle.com/projects/doodler-true-crime-podcast/chapter-one/',
  },
  {
    slug: 'the-doodler',
    date: '7 jul 1974',
    title: t('Klaus Christmann - Ocean Beach / Lincoln Way', 'Klaus Christmann - Ocean Beach / Lincoln Way'),
    category: 'body-recovery',
    location: t('Ocean Beach, pie de Lincoln Way', 'Ocean Beach, foot of Lincoln Way'),
    latitude: 37.7658,
    longitude: -122.5102,
    precision: t('Punto aproximado; Chronicle cita el pie de Lincoln Way.', 'Approximate point; Chronicle cites the foot of Lincoln Way.'),
    note: t('Lugar asociado al hallazgo de Klaus Christmann.', 'Area associated with Klaus Christmann recovery.'),
    sourceLabel: 'San Francisco Chronicle Doodler project',
    sourceUrl: 'https://www.sfchronicle.com/projects/doodler-true-crime-podcast/chapter-two/',
  },
  {
    slug: 'the-doodler',
    date: 'jul 1975',
    title: t('Fox Plaza Apartments', 'Fox Plaza Apartments'),
    category: 'suspect-lead',
    location: t('1390 Market Street, San Francisco', '1390 Market Street, San Francisco'),
    latitude: 37.7769,
    longitude: -122.4175,
    precision: t('Direccion exacta citada en folleto SFPD.', 'Exact address cited in SFPD flier.'),
    note: t('Dos ataques supervivientes ocurrieron en Fox Plaza; SFPD los vincula como linea investigativa del sospechoso.', 'Two survived attacks occurred at Fox Plaza; SFPD links them as part of the suspect line.'),
    sourceLabel: 'SFPD Doodler reward flier',
    sourceUrl: 'https://www.sanfranciscopolice.org/sites/default/files/2019-04/19-014%20Doodler%20Reward%20Flier.pdf',
  },
  {
    slug: 'the-doodler',
    date: 'jul 1975',
    title: t('1600 block de Market Street', '1600 block of Market Street'),
    category: 'suspect-lead',
    location: t('Market Street, San Francisco', 'Market Street, San Francisco'),
    latitude: 37.7745,
    longitude: -122.4214,
    precision: t('Bloque aproximado citado en folleto SFPD.', 'Approximate block cited in SFPD flier.'),
    note: t('Un superviviente dijo haber conocido al sospechoso en un antiguo diner nocturno de ese bloque.', 'A survivor said he met the suspect at a former all-night diner on this block.'),
    sourceLabel: 'SFPD Doodler reward flier',
    sourceUrl: 'https://www.sanfranciscopolice.org/sites/default/files/2019-04/19-014%20Doodler%20Reward%20Flier.pdf',
  },
]

export function getCaseMapPoints(slug: string) {
  return points.filter((point) => point.slug === slug)
}

export function localizeCaseMapPoint(point: CaseMapPoint, locale: Locale) {
  return {
    date: point.date,
    title: point.title[locale],
    category: point.category,
    location: point.location[locale],
    latitude: point.latitude,
    longitude: point.longitude,
    precision: point.precision[locale],
    note: point.note[locale],
    sourceLabel: point.sourceLabel,
    sourceUrl: point.sourceUrl,
  }
}
