import type { Locale } from './i18n'

export const landingCopy = {
  es: {
    marqueeItems: [
      'Comportamiento colectivo',
      'Ética digital',
      'Experimentos sociales',
      'Transparencia radical',
      'Datos anonimizados',
      'Ciencia abierta',
      'Psicología digital',
      'Sin lucro',
    ],
    manifestoLabel: 'Manifiesto',
    manifestoTitle: 'La tecnología revela lo que siempre estuvo ahí.',
    manifestoTitleEm: 'lo que siempre estuvo ahí.',
    manifestoP1: 'No creamos monstruos. Los descubrimos. Cada aplicación que lanzamos es un espejo, diseñado para reflejar con precisión los patrones de comportamiento que la sociedad prefiere ignorar.',
    manifestoP1Bold: 'Los descubrimos.',
    manifestoP2: 'Somos una empresa nueva. Nuestro primer experimento, WML 1.0, acaba de arrancar. Cuando termine, publicaremos todo: datos, análisis, conclusiones y lo que hayamos aprendido sobre nosotros mismos.',
    manifestoP2Bold: 'publicaremos todo',
    manifestoP3: 'La incomodidad es parte del diseño. El objetivo no es entretener, es entender.',
    principles: [
      { num: '01', title: 'Transparencia total', desc: 'Cada participante conoce exactamente en qué experimento está. El consentimiento informado no es letra pequeña, es el principio de todo.' },
      { num: '02', title: 'Fin definido', desc: 'Todo experimento tiene fecha de caducidad. Ninguna app vive más de lo necesario. Lanzamos, medimos, apagamos, publicamos.' },
      { num: '03', title: 'Datos anónimos', desc: 'Recopilamos patrones de comportamiento, nunca identidades. Los datos individuales se destruyen al finalizar cada experimento.' },
      { num: '04', title: 'Datos abiertos', desc: 'No vendemos datos individuales. No monetizamos usuarios específicos.' },
    ],
    expLabel: 'Experimentos',
    expTitle: 'Archivo de experimentos',
    expSubtitle: 'Todos los experimentos son opt-in, con duración máxima de 365 días y auditoría independiente.',
    experiments: [
      { id: 'wml1', num: 'WML-1.0', title: 'Karma Score', sub: 'Puntúa a otros usuarios positiva o negativamente. ¿Qué ocurre cuando todos tienen una nota pública?', status: 'active', statusLabel: 'En curso' },
      { id: 'wml2', num: 'WML-2.0', title: 'Yo no soy', sub: '¿Qué pasaría si las redes sociales fueran anónimas?', status: 'upcoming', statusLabel: 'Próximamente' },
      { id: 'wml3', num: 'WML-3.0', title: 'La ciudad sin memoria', sub: 'Red social donde todo contenido desaparece a las 24 horas, sin excepción.', status: 'upcoming', statusLabel: 'Próximamente' },
    ],
    howLabel: 'Metodología',
    howTitle: 'El proceso tiene estructura.',
    howDesc: 'Cada experimento sigue el mismo protocolo. Nada se improvisa, todo se publica.',
    steps: [
      { num: 1, title: 'Diseño', desc: 'Hipótesis, variables y límites éticos definidos antes de escribir una línea de código. Revisión por comité independiente.' },
      { num: 2, title: 'Consentimiento', desc: 'Los participantes conocen el experimento antes de entrar. Pueden abandonar en cualquier momento y borrar sus datos.' },
      { num: 3, title: 'Lanzamiento', desc: 'La app se activa. El equipo observa en tiempo real. Cualquier evento inesperado puede activar el cierre anticipado.' },
      { num: 4, title: 'Publicación', desc: 'Al finalizar, todos los datos anonimizados y conclusiones se pueden entregar a terceros.' },
    ],
    areasLabel: 'Categorías',
    areasTitle: 'Áreas de investigación',
    areasDesc: 'Los vectores donde la tecnología y la psicología humana colisionan con mayor intensidad.',
    areas: [
      { cat: 'Reputación y juicio', title: 'El peso de la nota', desc: '¿Cómo cambia el comportamiento cuando cada persona lleva una puntuación pública? Exploramos los efectos del juicio colectivo digitalizado.', status: 'WML 1.0 activo' },
      { cat: 'Anónimo', title: '¿Quién soy?', desc: '¿Cómo cambia nuestro comportamiento cuando nadie sabe quién está detrás del mensaje?', status: 'Planificado' },
      { cat: 'Memoria y olvido', title: 'La sociedad efímera', desc: 'El impacto del contenido permanente frente al efímero. ¿Somos más honestos cuando nada queda registrado?', status: 'Planificado' },
      { cat: 'Identidad digital', title: 'El yo construido', desc: 'Cuánto mostramos, cuánto ocultamos y qué precio pagamos por moldear nuestra identidad online.', status: 'En estudio' },
      { cat: 'Poder y control', title: 'Jerarquías emergentes', desc: 'Qué ocurre cuando damos a grupos sin entrenamiento herramientas para gobernarse o excluirse. ¿Cooperan o dominan?', status: 'En estudio' },
      { cat: 'Polarización', title: 'Fricciones calculadas', desc: 'Experimentos sobre burbujas ideológicas y qué ocurre cuando forzamos la exposición a perspectivas contrarias.', status: 'En estudio' },
    ],
    ethicsLabel: 'Marco ético',
    ethicsTitle: 'Distópico en forma. Ético en fondo.',
    ethicsDesc: 'La incomodidad de nuestros experimentos es intencional. El daño, jamás. Operamos bajo un marco de investigación estricto y con supervisión externa en cada proyecto.',
    ethicsItems: [
      { title: 'Revisión ética independiente', desc: 'Un comité externo revisa y aprueba cada diseño experimental antes de cualquier implementación técnica.' },
      { title: 'Derecho de abandono total', desc: 'Los participantes pueden retirarse en cualquier momento y solicitar la eliminación completa de sus datos sin justificarlo.' },
      { title: 'Límite temporal inamovible', desc: 'Ningún experimento puede extenderse. El cierre es automático y no requiere intervención humana.' },
      { title: 'Código abierto', desc: 'El código fuente de cada app es público durante el experimento. Cualquier investigador puede verificar su funcionamiento real.' },
      { title: 'Publicación obligatoria', desc: 'Publicaremos todos los resultados, incluso los que contradigan nuestra hipótesis o nos hagan quedar mal.' },
    ],
    ctaLabel: 'Únete',
    ctaTitle: 'Sé parte del próximo experimento.',
    ctaDesc: 'Recibirás notificaciones cuando lancemos nuevos experimentos. Tu participación siempre será voluntaria, informada y revocable.',
    ctaPlaceholder: 'tu@email.com',
    ctaBtn: 'Inscribirme',
    ctaDisclaimer: 'Sin spam. Solo ciencia incomoda.',
    ctaSuccess: 'Apuntado. Te avisamos cuando arranque el próximo experimento.',
    ctaError: 'Algo salió mal. Inténtalo de nuevo.',
    footerDesc: 'Exploramos los límites del comportamiento humano en entornos digitales. Con transparencia, ética y rigor científico.',
    footerLab: 'Laboratorio',
    footerCompany: 'Empresa',
    footerContact: 'Contacto',
    footerCopy: '2026 White Mirror Lab. Todos los experimentos cuentan con aprobación ética independiente.',
    footerPrivacy: 'Privacidad',
    footerEthics: 'Marco etico',
    footerLegalNotice: 'Aviso legal',
    footerTerms: 'Términos',
    navExperiments: 'Experimentos',
    navMethodology: 'Metodología',
    navAreas: 'Areas',
    navBlog: 'Blog',
    navEthics: 'Ética',
    navManifesto: 'Manifiesto',
    navJoin: 'Participar',
    navContact: 'Contacto',
    navDownload: 'WML-X.X.0',
    navMarketplace: 'Marketplace',
    navCreators: 'Creadores',
    navWml: 'WML-1.0',
    navWmlMenu: 'WML',
    navWmlOneSection: 'WML 0.0',
    navWmlExperimentalSection: 'WML X.X.X',
  },
  en: {
    marqueeItems: [
      'Collective behavior',
      'Digital ethics',
      'Social experiments',
      'Radical transparency',
      'Anonymized data',
      'Open science',
      'Digital psychology',
      'Non-profit',
    ],
    manifestoLabel: 'Manifesto',
    manifestoTitle: 'Technology reveals what was always there.',
    manifestoTitleEm: 'what was always there.',
    manifestoP1: "We do not create monsters. We discover them. Every app we launch is a mirror, designed to reflect the behavior patterns society prefers to ignore.",
    manifestoP1Bold: 'We discover them.',
    manifestoP2: "We are a new company. Our first experiment, WML 1.0, has just launched. When it ends, we will publish everything: data, analysis, conclusions, and what we have learned about ourselves.",
    manifestoP2Bold: 'we will publish everything',
    manifestoP3: 'Discomfort is part of the design. The goal is not to entertain, it is to understand.',
    principles: [
      { num: '01', title: 'Full transparency', desc: 'Every participant knows exactly which experiment they are in. Informed consent is not fine print, it is the starting point.' },
      { num: '02', title: 'Defined end date', desc: 'Every experiment has an expiry date. No app lives longer than necessary. We launch, measure, shut down, publish.' },
      { num: '03', title: 'Anonymous data', desc: 'We collect behavior patterns, never identities. Individual data is destroyed when each experiment ends.' },
      { num: '04', title: 'Open data', desc: 'We do not sell individual data. We do not monetize specific users.' },
    ],
    expLabel: 'Experiments',
    expTitle: 'Experiment archive',
    expSubtitle: 'All experiments are opt-in, with a maximum duration of 365 days and independent auditing.',
    experiments: [
      { id: 'wml1', num: 'WML-1.0', title: 'Karma Score', sub: 'Rate other users positively or negatively. What happens when everyone has a public score?', status: 'active', statusLabel: 'Active' },
      { id: 'wml2', num: 'WML-2.0', title: 'I Am Not', sub: 'What if social networks were anonymous?', status: 'upcoming', statusLabel: 'Coming soon' },
      { id: 'wml3', num: 'WML-3.0', title: 'The City Without Memory', sub: 'A social network where all content disappears after 24 hours, without exception.', status: 'upcoming', statusLabel: 'Coming soon' },
    ],
    howLabel: 'Methodology',
    howTitle: 'The process has structure.',
    howDesc: 'Every experiment follows the same protocol. Nothing is improvised, everything is published.',
    steps: [
      { num: 1, title: 'Design', desc: 'Hypotheses, variables, and ethical limits are defined before writing a single line of code. Reviewed by an independent committee.' },
      { num: 2, title: 'Consent', desc: 'Participants know the experiment before entering. They can leave at any time and delete their data.' },
      { num: 3, title: 'Launch', desc: 'The app goes live. The team observes in real time. Any unexpected event can trigger early closure.' },
      { num: 4, title: 'Publication', desc: 'At the end, all anonymized data and conclusions may be shared with third parties.' },
    ],
    areasLabel: 'Categories',
    areasTitle: 'Research areas',
    areasDesc: 'The vectors where technology and human psychology collide with the greatest intensity.',
    areas: [
      { cat: 'Reputation and judgment', title: 'The weight of the score', desc: 'How does behavior change when every person carries a public rating? We explore the effects of digitized collective judgment.', status: 'WML 1.0 active' },
      { cat: 'Anonymous', title: 'Who am I?', desc: 'How does our behavior change when nobody knows who is behind the message?', status: 'Planned' },
      { cat: 'Memory and forgetting', title: 'The ephemeral society', desc: 'Permanent versus ephemeral content. Are we more honest when nothing will be recorded?', status: 'Planned' },
      { cat: 'Digital identity', title: 'The constructed self', desc: 'How much we reveal, how much we hide, and what price we pay to shape our identity online.', status: 'In research' },
      { cat: 'Power and control', title: 'Emerging hierarchies', desc: 'What happens when we give untrained groups tools to govern or exclude. Do they cooperate or dominate?', status: 'In research' },
      { cat: 'Polarization', title: 'Calculated friction', desc: 'Experiments on ideological bubbles and what happens when we force exposure to opposing perspectives.', status: 'In research' },
    ],
    ethicsLabel: 'Ethics framework',
    ethicsTitle: 'Dystopian in form. Ethical in substance.',
    ethicsDesc: 'The discomfort of our experiments is intentional. Harm is not. We operate under a strict research framework with external oversight on every project.',
    ethicsItems: [
      { title: 'Independent ethics review', desc: 'An external committee reviews and approves every experimental design before any technical implementation.' },
      { title: 'Full right to withdraw', desc: 'Participants can withdraw at any time and request complete deletion of their data without justification.' },
      { title: 'Immovable time limit', desc: 'No experiment can be extended. Closure is automatic and requires no human intervention.' },
      { title: 'Open source', desc: 'The source code of each app is public during the experiment. Any researcher can verify how it works.' },
      { title: 'Mandatory publication', desc: 'We publish all results, even when they contradict our hypothesis or make us look bad.' },
    ],
    ctaLabel: 'Join',
    ctaTitle: 'Be part of the next experiment.',
    ctaDesc: 'You will receive notifications when we launch new experiments. Your participation will always be voluntary, informed, and revocable.',
    ctaPlaceholder: 'you@email.com',
    ctaBtn: 'Sign me up',
    ctaDisclaimer: 'No spam. Just uncomfortable science.',
    ctaSuccess: 'You are in. We will let you know when the next experiment starts.',
    ctaError: 'Something went wrong. Please try again.',
    footerDesc: 'We explore the limits of human behavior in digital environments. With transparency, ethics, and scientific rigor.',
    footerLab: 'Lab',
    footerCompany: 'Company',
    footerContact: 'Contact',
    footerCopy: '2026 White Mirror Lab. All experiments have independent ethics approval.',
    footerPrivacy: 'Privacy',
    footerEthics: 'Ethics framework',
    footerLegalNotice: 'Legal notice',
    footerTerms: 'Terms',
    navExperiments: 'Experiments',
    navMethodology: 'Methodology',
    navAreas: 'Areas',
    navBlog: 'Blog',
    navEthics: 'Ethics',
    navManifesto: 'Manifesto',
    navJoin: 'Join',
    navContact: 'Contact',
    navDownload: 'WML-X.X.0',
    navMarketplace: 'Marketplace',
    navCreators: 'Creators',
    navWml: 'WML-1.0',
    navWmlMenu: 'WML',
    navWmlOneSection: 'WML 0.0',
    navWmlExperimentalSection: 'WML X.X.X',
  },
} as const

export const downloadCopy = {
  es: {
    eyebrow: 'Widget de mascota para Windows',
    title: 'Tu escritorio también puede mirarte.',
    lead: 'WML X.X.0 es una mascota flotante para Windows que vive sobre tu escritorio, gana puntos con tu actividad local y te ayuda con IA local, sugerencias prácticas y tareas de optimización confirmadas sin leer lo que escribes.',
    petLabel: 'Mascotas',
    pet: 'Erizo y pato',
    pointsLabel: 'Puntos',
    points: 'Clics y teclado',
    downloadsLabel: 'Descargas',
    versionLabel: 'Versión',
    version: 'WML X.X.0',
    emailPlaceholder: 'tu@email.com',
    desktopCta: 'Suscribirme y descargar',
    desktopHint: 'La suscripción a la newsletter es obligatoria. Después verás una confirmación sobre cómo funciona el widget antes de iniciar la descarga.',
    creatorsTitle: 'Solo para creadores: gana dinero con WML X.X.0',
    creatorsText: 'Crea tus propias skins y véndelas en el marketplace. Haz dinero creando arte.',
    creatorsCta: 'Crear skins',
    subscribeSuccess: 'Suscripción confirmada. Revisa y acepta el funcionamiento del widget para descargar.',
    subscribeError: 'No hemos podido suscribirte. Inténtalo de nuevo.',
    invalidEmail: 'Introduce un email válido para descargar.',
    consentTitle: 'Antes de descargar',
    consentLead: 'Para descargar WML X.X.0 debes aceptar que entiendes como funciona el widget.',
    consentItems: [
      'La mascota reacciona a señales locales de actividad como clics y escritura, pero no lee el contenido que escribes.',
      'Puede observar batería, estado de la mascota, puntos, apps habituales y algunas señales básicas de seguridad.',
      'La IA local se prepara en tu ordenador, no necesita clave API ni internet para usarse una vez instalada.',
      'Puede analizar CPU, RAM, disco, batería y procesos seguros, ejecutar tareas de optimización, limpiar temporales, liberar RAM o enfocar apps habituales con confirmación.',
      'No envía archivos personales, texto escrito en otras apps ni contenido de ventanas a la IA local.',
      'Las sugerencias son limitadas, aparecen de una en una y las acciones que puedan afectarte requieren confirmación antes de ejecutarse.',
      'No sustituye a Microsoft Defender, un EDR ni un antivirus profesional.',
    ],
    consentCheckbox: 'Entiendo y acepto el funcionamiento descrito de WML X.X.0.',
    consentCta: 'Acepto y descargar',
    consentRequired: 'Debes aceptar el funcionamiento del widget para descargar.',
    requirementsTitle: 'Requisitos recomendados',
    requirements: [
      'Windows con conexión a internet solo para descargar o reparar la IA local.',
      '8-16 GB de RAM recomendados.',
      '15-30 GB libres para runtime, modelo, caches y trazas.',
      'Funciona en CPU; una GPU compatible mejora la latencia.',
    ],
    platformTitle: 'Elige tu sistema',
    platformLead: 'Después de aceptar, selecciona la versión de Windows.',
    windowsLabel: 'Windows',
    linuxLabel: 'Linux',
    linuxUnavailable: 'Próximamente',
    choosePlatform: 'Elige Windows para continuar.',
    closePopup: 'Cerrar',
    downloadThanksTitle: 'Muchas gracias por la descarga.',
    mobileDialogTitle: 'Necesitas un ordenador',
    mobileDialogText: 'Hemos guardado tu email, pero la descarga solo está disponible desde un ordenador Windows. Abre esta página desde tu PC para continuar.',
    mobileTitle: 'Descarga disponible solo en ordenador',
    mobileText: 'Abre esta página desde un ordenador Windows para descargar el widget de mascota WML X.X.0.',
    backHome: 'Volver al inicio',
    checks: [
      'Mascota flotante siempre visible, discreta y configurable.',
      'Tienda visual para comprar especies, colores y accesorios con puntos.',
      'Asistente de chat con IA local sin internet cuando termina su instalación.',
      'Tareas de optimización, batería, actividad, apps y seguridad con confirmación antes de actuar.',
    ],
  },
  en: {
    eyebrow: 'Desktop pet widget for Windows',
    title: 'Your desktop can watch back.',
    lead: 'WML X.X.0 is a floating pet for Windows that lives above your desktop, earns points from local activity, and helps with local AI, practical suggestions, and confirmed optimization tasks without reading what you type.',
    petLabel: 'Pets',
    pet: 'Hedgehog and duck',
    pointsLabel: 'Points',
    points: 'Clicks and typing',
    downloadsLabel: 'Downloads',
    versionLabel: 'Version',
    version: 'WML X.X.0',
    emailPlaceholder: 'you@email.com',
    desktopCta: 'Subscribe and download',
    desktopHint: 'Newsletter subscription is required. After that, you will review how the widget works before the download starts.',
    creatorsTitle: 'Creators only: earn money with WML X.X.0',
    creatorsText: 'Create your own skins and sell them in the marketplace. Make money creating art.',
    creatorsCta: 'Create skins',
    subscribeSuccess: 'Subscription confirmed. Review and accept how the widget works to download.',
    subscribeError: 'We could not subscribe you. Please try again.',
    invalidEmail: 'Enter a valid email to download.',
    consentTitle: 'Before downloading',
    consentLead: 'To download WML X.X.0, you must confirm that you understand how the widget works.',
    consentItems: [
      'The pet reacts to local activity signals such as clicks and typing, but it does not read what you type.',
      'It may observe battery state, pet state, points, common apps, and some basic security signals.',
      'Local AI is prepared on your computer and does not need an API key or internet once installed.',
      'It can analyze CPU, RAM, disk, battery, and safe processes, run optimization tasks, clean temporary files, free RAM, or focus common apps with confirmation.',
      'It does not send personal files, text typed in other apps, or window contents to the local AI.',
      'Suggestions are limited, appear one at a time, and actions that may affect you require confirmation before running.',
      'It does not replace Microsoft Defender, an EDR, or professional antivirus software.',
    ],
    consentCheckbox: 'I understand and accept the described behavior of WML X.X.0.',
    consentCta: 'Accept and download',
    consentRequired: 'You must accept how the widget works to download.',
    requirementsTitle: 'Recommended requirements',
    requirements: [
      'Windows with an internet connection only to download or repair local AI.',
      '8-16 GB RAM recommended.',
      '15-30 GB free for runtime, model, caches, and traces.',
      'Runs on CPU; a compatible GPU improves latency.',
    ],
    platformTitle: 'Choose your system',
    platformLead: 'After accepting, select the Windows version.',
    windowsLabel: 'Windows',
    linuxLabel: 'Linux',
    linuxUnavailable: 'Coming soon',
    choosePlatform: 'Choose Windows to continue.',
    closePopup: 'Close',
    downloadThanksTitle: 'Thank you so much for downloading.',
    mobileDialogTitle: 'You need a computer',
    mobileDialogText: 'We saved your email, but the download is only available from a Windows computer. Open this page from your PC to continue.',
    mobileTitle: 'Download available on desktop only',
    mobileText: 'Open this page from a Windows computer to download the WML X.X.0 desktop pet widget.',
    backHome: 'Back home',
    checks: [
      'Floating pet that stays visible, discreet, and configurable.',
      'Visual shop for species, colors, and accessories bought with points.',
      'Chat assistant with local AI without internet when installation finishes.',
      'Optimization, battery, activity, apps, and security tasks with confirmation before action.',
    ],
  },
} as const

export const skinTemplateCopy = {
  es: {
    eyebrow: 'Lanzamiento de creadores para WML X.X.0',
    title: 'Crea skins para WML.',
    lead: 'Cada creador puede diseñar su propia skin con el estilo que quiera: sprites, animaciones, personajes, mascotas, atuendos y previsualizaciones. Después solo tendrá que empaquetarla siguiendo la plantilla oficial.',
    downloadCta: 'Descargar plantilla',
    downloadHint: 'Descarga la plantilla oficial para preparar los .pet, .clothes, .json, las previsualizaciones y el zip final del marketplace.',
    desktopOnlyHint: 'La plantilla solo se puede descargar desde un ordenador. Abre esta página en PC o portátil para descargarla.',
    widgetTitle: 'Conectado al widget',
    widgetText: 'Publica tu pack en el marketplace.',
    widgetBody: 'Cuando un pack sea aprobado, los usuarios podrán descargarlo en formato zip e importarlo en la app de escritorio.',
    widgetCta: 'Descargar widget',
    galleryLabel: 'Referencias',
    galleryTitle: 'Cualquier estilo, una estructura común.',
    galleryText: 'El arte es libre: pixel art, ilustración, coleccionable 3D, peluche, dibujo animado o lo que encaje con tu pack. La plantilla solo ordena archivos y datos para que la app pueda leerlo.',
    characterTones: ['Juguete cromado', 'Estilo suave', 'Pack ilustrado', 'Skin pixel art'],
    swatches: ['.pet', '.clothes', '.json', '.zip'],
    backHome: 'Volver al inicio',
    stepsTitle: 'Flujo de creador',
    steps: [
      {
        title: 'Diseña tu pack',
        desc: 'Crea cada sprite y animación con tu propio estilo. Puedes hacer mascotas, atuendos, accesorios o una colección completa.',
      },
      {
        title: 'Sigue la plantilla',
        desc: 'Prepara los archivos .pet, .clothes, .json y las previsualizaciones según la estructura oficial para que el pack sea instalable.',
      },
      {
        title: 'Envía el zip',
        desc: 'Comprime el pack y envíalo por el canal que anunciaremos. Lo revisaremos y, si está correcto, se subirá al marketplace.',
      },
    ],
    detailsTitle: 'Cómo se organiza',
    details: [
      'Un archivo .pet añade una mascota al pack.',
      'Un archivo .clothes contiene atuendos o ropa.',
      'Los .json describen datos, nombres, previsualizaciones y comportamiento.',
      'El pack final se enviará en formato zip para revisión.',
    ],
    coffeeTitle: 'Apoya el kit de creadores',
    coffeeText: 'El formulario oficial de Buy Me a Coffee está abierto directamente aquí para apoyar el kit de creadores.',
    statusLabel: 'Estado',
    statusValue: 'Plantilla disponible; canal de envío pendiente',
  },
  en: {
    eyebrow: 'Creator drop for WML X.X.0',
    title: 'Create skins for WML.',
    lead: 'Each creator can design their own skin in any style: sprites, animations, characters, pets, outfits, and previews. After that, they only need to package it using the official template.',
    downloadCta: 'Download template',
    downloadHint: 'Download the official template to prepare the .pet, .clothes, .json, previews, and final marketplace zip.',
    desktopOnlyHint: 'The template can only be downloaded from a computer. Open this page on a desktop or laptop to download it.',
    widgetTitle: 'Connected to the widget',
    widgetText: 'Publish your pack in the marketplace.',
    widgetBody: 'Once a pack is approved, users will be able to download it as a zip file and import it into the desktop app.',
    widgetCta: 'Download widget',
    galleryLabel: 'Moodboard',
    galleryTitle: 'Any style, one shared structure.',
    galleryText: 'The art is open: pixel art, illustration, 3D collectible, plush, cartoon, or whatever fits your pack. The template only organizes files and data so the app can read them.',
    characterTones: ['Chrome toy', 'Soft drop', 'Sketch pack', 'Pixel skin'],
    swatches: ['.pet', '.clothes', '.json', '.zip'],
    backHome: 'Back home',
    stepsTitle: 'Creator flow',
    steps: [
      {
        title: 'Design your pack',
        desc: 'Create every sprite and animation in your own style. You can make pets, outfits, accessories, or a full collection.',
      },
      {
        title: 'Follow the template',
        desc: 'Prepare the .pet, .clothes, .json, and preview files using the official structure so the pack can be installed.',
      },
      {
        title: 'Submit the zip',
        desc: 'Compress the pack and send it through the channel we announce. We will review it and, if it is correct, upload it to the marketplace.',
      },
    ],
    detailsTitle: 'How it is organized',
    details: [
      'A .pet file adds a pet to the pack.',
      'A .clothes file contains outfits or clothing.',
      'The .json files describe data, names, previews, and behavior.',
      'The final pack will be submitted as a zip file for review.',
    ],
    coffeeTitle: 'Support the creator kit',
    coffeeText: 'The official Buy Me a Coffee form is open directly here to support the creator kit.',
    statusLabel: 'Status',
    statusValue: 'Template available; submission channel pending',
  },
} as const

export const heroCopy = {
  es: {
    tag: 'Laboratorio de experimentación social',
    line1: 'Qué hace',
    line2: 'el ser humano',
    line3pre: 'cuando',
    line3accent: 'nadie',
    line4: 'lo observa?',
    desc: 'Diseñamos aplicaciones que empujan los límites del comportamiento colectivo. Experimentos sociales controlados, éticos y temporales que revelan verdades incómodas de nuestra naturaleza digital.',
    ctaPrimary: 'Participa',
    ctaGhost: 'Invítame a un café',
    statParticipants: 'Participantes',
    statExperiments: 'Experimentos',
    statOptin: 'Opt-in',
  },
  en: {
    tag: 'Social experimentation lab',
    line1: 'What does',
    line2: 'the human being',
    line3pre: 'do when',
    line3accent: 'nobody',
    line4: 'is watching?',
    desc: 'We design applications that push the limits of collective behavior. Controlled, ethical, time-limited social experiments that reveal uncomfortable truths about our digital nature.',
    ctaPrimary: 'Join',
    ctaGhost: 'Buy me a coffee',
    statParticipants: 'Participants',
    statExperiments: 'Experiments',
    statOptin: 'Opt-in',
  },
} as const

export const wmlCopy = {
  es: {
    
    backHome: 'Inicio',
    backHomeLabel: 'Volver al inicio',
    access: 'Acceso',
    consent: 'Consentimiento',
    feed: 'Feed',
    ranking: 'Ranking',
    search: 'Buscar',
    profile: 'Perfil',
    logout: 'Salir',
    loadingExperiment: 'Cargando experimento...',
    loadingProfile: 'Cargando perfil...',
    loadingRanking: 'Cargando ranking...',
    loadingYourProfile: 'Cargando tu perfil...',
    feedBannerTitle: 'Consigue votos para tu karma',
    feedBannerText: 'Comparte tu perfil en WhatsApp o Instagram y pide a otros que voten anónimamente.',
    feedBannerLink: 'Ir a mi perfil y compartir ->',
    participants: 'Participantes',
    noParticipants: 'Aún no hay más participantes. Invita a alguien al experimento.',
    rankingTitle: 'Ranking / Karma Score',
    rankingText: 'El participante con mayor karma al final del experimento recibirá el premio. Los votos son anónimos; por cada 5 negativos sumarás tú 1 de karma, por cada 8 positivos también lo sumarás.',
    searchUsers: 'Buscar usuarios',
    searchPlaceholder: 'Username o nombre...',
    noUsersFound: 'No se encontraron usuarios.',
    positive: 'Positivo',
    negative: 'Negativo',
    positivePlural: 'positivos',
    negativePlural: 'negativos',
    stories: 'Historias / 24h',
    yourStory: 'Tu historia',
    uploadStoryError: 'Error al subir historia',
    photosTitle: 'Fotos / max. 5',
    photosReplaceHint: '(la más antigua se borra al subir una nueva)',
    newPhoto: 'Nueva\n(reemplaza)',
    uploadPhotoError: 'Error al subir foto',
    publicProfileLink: 'Ver página pública ->',
    profileNotFound: 'Usuario no encontrado.',
    shareProfile: 'Comparte tu perfil',
    shareDesc: 'Pide votos anónimos. Quien abra tu enlace puede votarte tras unirse al experimento.',
    yourLink: 'Tu enlace',
    copied: 'Copiado',
    copy: 'Copiar',
    shareHint: 'Instagram: copiamos el enlace. Pégalo en tu historia o bio.',
    ownProfileHint: 'Este es tu perfil. Compártelo para recibir votos.',
    voteCta: 'Tu voto es anónimo. ¿Qué karma le das?',
    guestCta: 'Entra al experimento y vota de forma anónima.',
    joinAndVote: 'Entrar y votar',
    consentRequired: 'Debes aceptar todas las condiciones para continuar.',
    consentTitle: 'Consentimiento informado',
    consentBadge: 'WML 1.0 / Karma Score',
    consentHeading: 'Antes de participar',
    consentLead: 'WML 1.0 es un experimento social de reputación digital conducido por White Mirror Lab. Tu participación es voluntaria y puedes retirarte en cualquier momento cerrando sesión o solicitando la eliminación de tus datos.',
    consentInfoTitle: 'Qué implica participar',
    consentBullets: [
      'Recibirás votos positivos o negativos de otros participantes de forma anónima.',
      'Tu karma y los votos recibidos serán visibles públicamente.',
      'Nadie podrá ver a quién has votado tú, pero sí cuántos votos has recibido.',
      'Puedes subir hasta 5 fotos y publicar historias que desaparecen a las 24 horas.',
      'Al finalizar el experimento, publicaremos un análisis agregado y anónimo.',
    ],
    consentAge: 'Confirmo que tengo 18 años o más y capacidad legal para participar.',
    consentVoluntary: 'Entiendo que mi participación es voluntaria y que puedo retirarme sin penalización en cualquier momento.',
    consentTermsPrefix: 'He leído y acepto los',
    terms: 'Términos de participación',
    ethicsFramework: 'Marco ético del experimento',
    consentPrivacyPrefix: 'He leído y acepto la',
    privacyPolicy: 'Política de privacidad',
    cookiesPolicy: 'Política de cookies',
    acceptAndJoin: 'Acepto y quiero participar',
    dataController: 'Responsable del tratamiento: White Mirror Lab',
    legalNotice: 'Aviso legal',
    authTitleLogin: 'Acceder',
    authTitleSignup: 'Crear cuenta',
    authSubLogin: 'Entra al experimento.',
    authSubSignup: 'Únete al experimento. Tu karma empieza en 0.',
    authSignupParticipants: 'Únete a {count} participantes.',
    usernameRule: 'Username: 3-20 caracteres, solo minúsculas, números y _',
    usernameTaken: 'Ese username ya está en uso',
    confirmEmail: 'Cuenta creada. Confirma tu email desde el enlace que te hemos enviado y luego inicia sesión.',
    displayName: 'Nombre visible',
    password: 'Contraseña',
    noAccount: '¿No tienes cuenta?',
    haveAccount: '¿Ya tienes cuenta?',
    signup: 'Regístrate',
  },
  en: {
    backHome: 'Home',
    backHomeLabel: 'Back home',
    access: 'Access',
    consent: 'Consent',
    feed: 'Feed',
    ranking: 'Ranking',
    search: 'Search',
    profile: 'Profile',
    logout: 'Log out',
    loadingExperiment: 'Loading experiment...',
    loadingProfile: 'Loading profile...',
    loadingRanking: 'Loading ranking...',
    loadingYourProfile: 'Loading your profile...',
    feedBannerTitle: 'Get votes for your karma',
    feedBannerText: 'Share your profile on WhatsApp or Instagram and ask others to vote anonymously.',
    feedBannerLink: 'Go to my profile and share ->',
    participants: 'Participants',
    noParticipants: 'There are no more participants yet. Invite someone to the experiment.',
    rankingTitle: 'Ranking / Karma Score',
    rankingText: 'The participant with the highest karma at the end of the experiment will receive the prize. Voting is anonymous; for every 5 negative votes, you will gain 1 karma point, and for every 8 positive votes, you will also gain 1 point.',
    searchUsers: 'Search users',
    searchPlaceholder: 'Username or name...',
    noUsersFound: 'No users found.',
    positive: 'Positive',
    negative: 'Negative',
    positivePlural: 'positive',
    negativePlural: 'negative',
    stories: 'Stories / 24h',
    yourStory: 'Your story',
    uploadStoryError: 'Error uploading story',
    photosTitle: 'Photos / max. 5',
    photosReplaceHint: '(the oldest photo is deleted when you upload a new one)',
    newPhoto: 'New\n(replaces)',
    uploadPhotoError: 'Error uploading photo',
    publicProfileLink: 'View public page ->',
    profileNotFound: 'User not found.',
    shareProfile: 'Share your profile',
    shareDesc: 'Ask for anonymous votes. Anyone opening your link can vote after joining the experiment.',
    yourLink: 'Your link',
    copied: 'Copied',
    copy: 'Copy',
    shareHint: 'Instagram: we copy the link. Paste it into your story or bio.',
    ownProfileHint: 'This is your profile. Share it to receive votes.',
    voteCta: 'Your vote is anonymous. What karma do you give?',
    guestCta: 'Enter the experiment and vote anonymously.',
    joinAndVote: 'Enter and vote',
    consentRequired: 'You must accept all conditions to continue.',
    consentTitle: 'Informed consent',
    consentBadge: 'WML 1.0 / Karma Score',
    consentHeading: 'Before participating',
    consentLead: 'WML 1.0 is a digital reputation social experiment run by White Mirror Lab. Your participation is voluntary and you can withdraw at any time by signing out or requesting deletion of your data.',
    consentInfoTitle: 'What participation involves',
    consentBullets: [
      'You will receive positive or negative votes from other participants anonymously.',
      'Your karma and received votes will be publicly visible.',
      'Nobody can see who you voted for, but they can see how many votes you received.',
      'You can upload up to 5 photos and publish stories that disappear after 24 hours.',
      'When the experiment ends, we will publish aggregated and anonymous analysis.',
    ],
    consentAge: 'I confirm that I am 18 or older and legally able to participate.',
    consentVoluntary: 'I understand that my participation is voluntary and that I can withdraw at any time without penalty.',
    consentTermsPrefix: 'I have read and accept the',
    terms: 'Participation terms',
    ethicsFramework: 'Ethics framework',
    consentPrivacyPrefix: 'I have read and accept the',
    privacyPolicy: 'Privacy policy',
    cookiesPolicy: 'Cookie policy',
    acceptAndJoin: 'I accept and want to participate',
    dataController: 'Data controller: White Mirror Lab',
    legalNotice: 'Legal notice',
    authTitleLogin: 'Sign in',
    authTitleSignup: 'Create account',
    authSubLogin: 'Enter the experiment.',
    authSubSignup: 'Join the experiment. Your karma starts at 0.',
    authSignupParticipants: 'Join {count} participants.',
    usernameRule: 'Username: 3-20 characters, lowercase letters, numbers, and _ only',
    usernameTaken: 'That username is already taken',
    confirmEmail: 'Account created. Confirm your email from the link we sent you, then sign in.',
    displayName: 'Display name',
    password: 'Password',
    noAccount: 'No account?',
    haveAccount: 'Already have an account?',
    signup: 'Sign up',
  },
} as const

export function getCopy<T extends Record<Locale, unknown>>(copy: T, locale: Locale): T[Locale] {
  return copy[locale]
}
