import type { Locale } from './i18n'

export const landingCopy = {
  es: {
    marqueeItems: [
      'Mascota de escritorio',
      'Ética digital',
      'IA local',
      'Señales mínimas',
      'Privacidad por diseño',
      'Juguete raro',
      'Nostalgia inquieta',
      'Windows',
    ],
    manifestoLabel: 'Manifiesto',
    manifestoTitle: 'Un juguete de escritorio para no mirar siempre hacia fuera.',
    manifestoTitleEm: 'no mirar siempre hacia fuera.',
    manifestoP1: 'No queremos una app que espíe la vida de nadie. WML X.X.0 trabaja en local, con señales pequeñas del dispositivo, para probar si una mascota digital puede hacer más amable la rutina sin volverse invasiva.',
    manifestoP1Bold: 'trabaja en local',
    manifestoP2: 'El experimento principal ahora es WML X.X.0: una mascota flotante para el escritorio, con IA local, puntos, skins y acciones que siempre piden confirmación.',
    manifestoP2Bold: 'WML X.X.0',
    manifestoP3: 'La estética puede dar mal rollo. La práctica no: datos mínimos, explicación clara y control del usuario.',
    principles: [
      { num: '01', title: 'Local primero', desc: 'La mascota reacciona a señales del propio ordenador. No lee conversaciones, documentos ni lo que escribes en otras apps.' },
      { num: '02', title: 'Acciones confirmadas', desc: 'Las sugerencias pueden ayudar con batería, foco o limpieza básica, pero cualquier acción sensible requiere permiso antes de ejecutarse.' },
      { num: '03', title: 'Datos mínimos', desc: 'La web usa email para descarga/newsletter y analítica opcional. El widget se explica antes de descargarlo.' },
      { num: '04', title: 'Diseño honesto', desc: 'El producto puede parecer un juguete extraño, pero sus límites deben ser fáciles de entender y de rechazar.' },
    ],
    expLabel: 'Experimentos',
    expTitle: 'Experimento principal',
    expSubtitle: 'WML X.X.0 concentra ahora el laboratorio: compañía local, IA en tu equipo, skins y señales de actividad no invasivas.',
    experiments: [
      { id: 'wmlxx0', num: 'WML-X.X.0', title: 'Mascota local', sub: 'Un compañero flotante para Windows que convierte actividad local en puntos, skins y ayuda práctica.', status: 'active', statusLabel: 'Principal' },
      { id: 'blog', num: 'BLOG', title: 'Blog', sub: 'Un blog editorial convertido en experiencia jugable, ruido visual y pequeñas ventanas de atención.', status: 'active', statusLabel: 'Activo' },
      { id: 'wml1archive', num: 'WML-1.0', title: 'Resultados', sub: 'El experimento anterior queda como archivo. Sus resultados se publicarán en una página independiente.', status: 'upcoming', statusLabel: 'Archivo' },
    ],
    howLabel: 'Metodología',
    howTitle: 'El proceso empieza por el límite.',
    howDesc: 'Probamos una presencia digital pequeña, con alcance limitado y comprensible antes de instalar.',
    steps: [
      { num: 1, title: 'Instalar', desc: 'La descarga explica qué señales puede usar el widget y qué no toca: archivos personales, texto escrito y contenido de ventanas.' },
      { num: 2, title: 'Convivir', desc: 'La mascota vive encima del escritorio, reacciona a actividad local y suma puntos para desbloquear especies, colores y accesorios.' },
      { num: 3, title: 'Ayudar', desc: 'La IA local puede sugerir tareas de foco, batería u optimización. Las acciones que afecten al sistema se confirman una a una.' },
      { num: 4, title: 'Ajustar', desc: 'El experimento evoluciona desde feedback, incidencias y métricas agregadas de la web, no desde seguimiento personal indiscriminado.' },
    ],
    areasLabel: 'Categorías',
    areasTitle: 'Qué estamos probando',
    areasDesc: 'Un escritorio con una presencia juguetona, útil y un poco inquietante, pero con límites técnicos claros.',
    areas: [
      { cat: 'Compañía local', title: 'Presencia de escritorio', desc: 'Cómo cambia la relación con el ordenador cuando una mascota pequeña acompaña tareas repetitivas sin reclamar atención constante.', status: 'WML X.X.0' },
      { cat: 'Puntos', title: 'Rutina convertida en juego', desc: 'Clics, teclado y actividad local se transforman en progresión visual, sin leer el contenido de lo que haces.', status: 'Activo' },
      { cat: 'IA local', title: 'Ayuda sin nube', desc: 'Un asistente preparado en el propio equipo para responder y sugerir acciones básicas cuando el usuario lo pide.', status: 'Activo' },
      { cat: 'Skins', title: 'Familia de personajes', desc: 'Especies, colores, accesorios y packs de creadores dan identidad al widget sin cambiar sus límites de privacidad.', status: 'Marketplace' },
      { cat: 'Seguridad básica', title: 'Avisos pequeños', desc: 'Señales de batería, rendimiento o procesos seguros pueden activar sugerencias, siempre explicadas y confirmadas.', status: 'En pruebas' },
      { cat: 'Archivo', title: 'WML 1.0 cerrado', desc: 'La línea de reputación pública deja de ser el foco del sitio y queda reservada para la página de resultados.', status: 'Resultados pronto' },
    ],
    ethicsLabel: 'Marco ético',
    ethicsTitle: 'Creepy en forma. Claro en fondo.',
    ethicsDesc: 'El mal rollo es visual, no legal ni técnico. WML X.X.0 debe sentirse raro sin cruzar la línea de leer, enviar o actuar sobre información personal sin permiso.',
    ethicsItems: [
      { title: 'Consentimiento antes de descargar', desc: 'La página de descarga enumera las capacidades del widget antes de iniciar el instalador.' },
      { title: 'Sin lectura de contenido', desc: 'No enviamos a la IA local archivos personales, texto escrito en otras apps ni contenido de ventanas.' },
      { title: 'Control del usuario', desc: 'Las tareas de optimización, foco o limpieza requieren confirmación cuando pueden afectar al equipo.' },
      { title: 'Analítica separada', desc: 'La analítica web no esencial depende del panel de cookies y puede rechazarse.' },
      { title: 'Archivo responsable', desc: 'WML 1.0 queda apartado del relato activo hasta publicar resultados con contexto y datos agregados.' },
    ],
    ctaLabel: 'Descarga',
    ctaTitle: '¿Solo con tu ordenador?',
    ctaDesc: 'Recibe el enlace de WML X.X.0, revisa cómo funciona la mascota y descarga la versión de Windows.',
    ctaPlaceholder: 'tu@email.com',
    ctaBtn: 'Recibir descarga',
    ctaDisclaimer: 'Sin spam. Solo avisos del widget, skins y cambios importantes.',
    ctaSuccess: 'Listo. Te llevamos a la descarga de WML X.X.0.',
    ctaError: 'Algo salió mal. Inténtalo de nuevo.',
    footerDesc: 'Construimos experimentos digitales pequeños, raros y explícitos. WML X.X.0 es ahora el centro del laboratorio.',
    footerLab: 'Laboratorio',
    footerCompany: 'Empresa',
    footerContact: 'Contacto',
    footerCopy: '2026 White Mirror Lab. Privacidad por diseño, consentimiento claro y estética de juguete torcido.',
    footerPrivacy: 'Privacidad',
    footerEthics: 'Marco etico',
    footerLegalNotice: 'Aviso legal',
    footerTerms: 'Términos',
    navExperiments: 'Experimentos',
    navAreas: 'Areas',
    navBlog: 'Blog',
    navFaro: 'FARO',
    navManifesto: 'Manifiesto',
    navJoin: 'Descargar',
    navContact: 'Contacto',
    navDownload: 'WML-X.X.0',
    navMarketplace: 'Marketplace',
    navCreators: 'Creadores',
    navWml: 'WML-1.0',
    navWmlMenu: 'WML',
    navWmlOneSection: 'Archivo',
    navWmlExperimentalSection: 'WML X.X.X',
  },
  en: {
    marqueeItems: [
      'Desktop pet',
      'Digital ethics',
      'Local AI',
      'Minimal signals',
      'Privacy by design',
      'Odd toy',
      'Uneasy nostalgia',
      'Windows',
    ],
    manifestoLabel: 'Manifesto',
    manifestoTitle: 'A desktop toy for not always looking outward.',
    manifestoTitleEm: 'not always looking outward.',
    manifestoP1: "We do not want an app that spies on anyone's life. WML X.X.0 works locally, with small device signals, to test whether a digital pet can make routine gentler without becoming invasive.",
    manifestoP1Bold: 'works locally',
    manifestoP2: 'The main experiment is now WML X.X.0: a floating desktop pet, with local AI, points, skins, and actions that always ask for confirmation.',
    manifestoP2Bold: 'WML X.X.0',
    manifestoP3: 'The look may feel unsettling. The practice should not: minimal data, plain explanations, and user control.',
    principles: [
      { num: '01', title: 'Local first', desc: 'The pet reacts to signals from the computer itself. It does not read conversations, documents, or what you type in other apps.' },
      { num: '02', title: 'Confirmed actions', desc: 'Suggestions may help with battery, focus, or basic cleanup, but sensitive actions ask before running.' },
      { num: '03', title: 'Minimal data', desc: 'The website uses email for download/newsletter and optional analytics. The widget behavior is explained before downloading.' },
      { num: '04', title: 'Honest design', desc: 'The product can look like a strange toy, but its limits should be easy to understand and refuse.' },
    ],
    expLabel: 'Experiments',
    expTitle: 'Main experiment',
    expSubtitle: 'WML X.X.0 is now the center of the lab: local pet, on-device AI, skins, and non-invasive activity signals.',
    experiments: [
      { id: 'wmlxx0', num: 'WML-X.X.0', title: 'Local pet', sub: 'A floating Windows companion that turns local activity into points, skins, and practical help.', status: 'active', statusLabel: 'Main' },
      { id: 'blog', num: 'BLOG', title: 'Blog', sub: 'An editorial blog turned into a playable experience, visual noise, and small windows of attention.', status: 'active', statusLabel: 'Active' },
      { id: 'wml1archive', num: 'WML-1.0', title: 'Results', sub: 'The previous experiment remains as an archive. Its results will be published on a dedicated page.', status: 'upcoming', statusLabel: 'Archive' },
    ],
    howLabel: 'Methodology',
    howTitle: 'The process starts with the limit.',
    howDesc: 'We are testing a small digital presence with a limited scope that must be clear before installation.',
    steps: [
      { num: 1, title: 'Install', desc: 'The download explains which signals the widget may use and what it does not touch: personal files, typed text, and window contents.' },
      { num: 2, title: 'Coexist', desc: 'The pet lives above the desktop, reacts to local activity, and earns points for species, colors, and accessories.' },
      { num: 3, title: 'Assist', desc: 'Local AI can suggest focus, battery, or optimization tasks. Actions that affect the system are confirmed one by one.' },
      { num: 4, title: 'Adjust', desc: 'The experiment evolves from feedback, issues, and aggregate website metrics, not indiscriminate personal tracking.' },
    ],
    areasLabel: 'Categories',
    areasTitle: 'What we are testing',
    areasDesc: 'A desktop with a playful, useful, slightly unsettling presence, but with clear technical boundaries.',
    areas: [
      { cat: 'Local companion', title: 'Desktop presence', desc: 'How the computer feels when a small pet accompanies repetitive work without constantly asking for attention.', status: 'WML X.X.0' },
      { cat: 'Points', title: 'Routine as play', desc: 'Clicks, keyboard activity, and local signals become visual progression without reading the content of what you do.', status: 'Active' },
      { cat: 'Local AI', title: 'Help without cloud', desc: 'An assistant prepared on the device to answer and suggest basic actions when the user asks.', status: 'Active' },
      { cat: 'Skins', title: 'Character family', desc: 'Species, colors, accessories, and creator packs give identity to the widget without changing privacy limits.', status: 'Marketplace' },
      { cat: 'Basic safety', title: 'Small warnings', desc: 'Battery, performance, or safe process signals may trigger suggestions, always explained and confirmed.', status: 'Testing' },
      { cat: 'Archive', title: 'WML 1.0 closed', desc: 'The public reputation line is no longer the site focus and is reserved for the results page.', status: 'Results soon' },
    ],
    ethicsLabel: 'Ethics framework',
    ethicsTitle: 'Creepy in form. Clear in substance.',
    ethicsDesc: 'The unease is visual, not legal or technical. WML X.X.0 should feel strange without reading, sending, or acting on personal information without permission.',
    ethicsItems: [
      { title: 'Consent before download', desc: 'The download page lists the widget capabilities before starting the installer.' },
      { title: 'No content reading', desc: 'We do not send personal files, text typed in other apps, or window contents to local AI.' },
      { title: 'User control', desc: 'Optimization, focus, or cleanup tasks require confirmation when they can affect the computer.' },
      { title: 'Separate analytics', desc: 'Non-essential website analytics depends on the cookie panel and can be rejected.' },
      { title: 'Responsible archive', desc: 'WML 1.0 is separated from the active story until results are published with context and aggregate data.' },
    ],
    ctaLabel: 'Download',
    ctaTitle: 'Alone with your computer?',
    ctaDesc: 'Get the WML X.X.0 link, review how the pet works, and download the Windows version.',
    ctaPlaceholder: 'you@email.com',
    ctaBtn: 'Get download',
    ctaDisclaimer: 'No spam. Only widget, skin, and important update notes.',
    ctaSuccess: 'Done. We are taking you to the WML X.X.0 download.',
    ctaError: 'Something went wrong. Please try again.',
    footerDesc: 'We build small, strange, explicit digital experiments. WML X.X.0 is now the center of the lab.',
    footerLab: 'Lab',
    footerCompany: 'Company',
    footerContact: 'Contact',
    footerCopy: '2026 White Mirror Lab. Privacy by design, clear consent, and crooked toy aesthetics.',
    footerPrivacy: 'Privacy',
    footerEthics: 'Ethics framework',
    footerLegalNotice: 'Legal notice',
    footerTerms: 'Terms',
    navExperiments: 'Experiments',
    navAreas: 'Areas',
    navBlog: 'Blog',
    navFaro: 'FARO',
    navManifesto: 'Manifesto',
    navJoin: 'Download',
    navContact: 'Contact',
    navDownload: 'WML-X.X.0',
    navMarketplace: 'Marketplace',
    navCreators: 'Creators',
    navWml: 'WML-1.0',
    navWmlMenu: 'WML',
    navWmlOneSection: 'Archive',
    navWmlExperimentalSection: 'WML X.X.X',
  },
} as const

export const downloadCopy = {
  es: {
    eyebrow: 'Widget de mascota para Windows',
    title: '¿Estás muy solo con tu ordenador?',
    lead: 'WML X.X.0 es una mascota flotante para Windows que vive sobre tu escritorio: gana puntos con señales locales, desbloquea skins y te ayuda con IA local sin leer lo que escribes.',
    petLabel: 'Mascotas',
    pet: 'Erizo y pato',
    pointsLabel: 'Puntos',
    points: 'Clics y teclado',
    downloadsLabel: 'Descargas',
    versionLabel: 'Versión',
    version: 'WML X.X.0',
    emailPlaceholder: 'tu@email.com',
    desktopCta: 'Suscribirme y descargar',
    desktopHint: 'La suscripción a la newsletter es obligatoria. Después verás una confirmación sobre cómo funciona el widget antes de iniciar la descarga.',
    creatorsTitle: 'Solo para creadores: gana dinero con WML X.X.0',
    creatorsText: 'Crea tus propias skins y véndelas en el marketplace. Haz dinero creando arte.',
    creatorsCta: 'Crear skins',
    subscribeSuccess: 'Suscripción confirmada. Revisa y acepta el funcionamiento del widget para descargar.',
    subscribeError: 'No hemos podido suscribirte. Inténtalo de nuevo.',
    invalidEmail: 'Introduce un email válido para descargar.',
    consentTitle: 'Antes de descargar',
    consentLead: 'Para descargar WML X.X.0 debes aceptar que entiendes como funciona el widget.',
    consentItems: [
      'La mascota reacciona a señales locales de actividad como clics y escritura, pero no lee el contenido que escribes.',
      'Puede usar batería, estado de la mascota, puntos, apps habituales y algunas señales básicas de seguridad.',
      'La IA local se prepara en tu ordenador, no necesita clave API ni internet para usarse una vez instalada.',
      'Puede analizar CPU, RAM, disco, batería y procesos seguros, ejecutar tareas de optimización, limpiar temporales, liberar RAM o enfocar apps habituales con confirmación.',
      'No envía archivos personales, texto escrito en otras apps ni contenido de ventanas a la IA local.',
      'Las sugerencias son limitadas, aparecen de una en una y las acciones que puedan afectarte requieren confirmación antes de ejecutarse.',
      'No sustituye a Microsoft Defender, un EDR ni un antivirus profesional.',
    ],
    consentCheckbox: 'Entiendo y acepto el funcionamiento descrito de WML X.X.0.',
    consentCta: 'Acepto y descargar',
    consentRequired: 'Debes aceptar el funcionamiento del widget para descargar.',
    requirementsTitle: 'Requisitos recomendados',
    requirements: [
      'Windows con conexión a internet solo para descargar o reparar la IA local.',
      '8-16 GB de RAM recomendados.',
      '15-30 GB libres para runtime, modelo, caches y trazas.',
      'Funciona en CPU; una GPU compatible mejora la latencia.',
    ],
    platformTitle: 'Elige tu sistema',
    platformLead: 'Después de aceptar, selecciona la versión de Windows.',
    windowsLabel: 'Windows',
    linuxLabel: 'Linux',
    linuxUnavailable: 'Próximamente',
    choosePlatform: 'Elige Windows para continuar.',
    closePopup: 'Cerrar',
    downloadThanksTitle: 'Muchas gracias por la descarga.',
    mobileDialogTitle: 'Necesitas un ordenador',
    mobileDialogText: 'Hemos guardado tu email, pero la descarga solo está disponible desde un ordenador Windows. Abre esta página desde tu PC para continuar.',
    mobileTitle: 'Descarga disponible solo en ordenador',
    mobileText: 'Abre esta página desde un ordenador Windows para descargar el widget de mascota WML X.X.0.',
    backHome: 'Volver al inicio',
    checks: [
      'Mascota flotante siempre visible, discreta y configurable.',
      'Tienda visual para comprar especies, colores y accesorios con puntos.',
      'Asistente de chat con IA local sin internet cuando termina su instalación.',
      'Tareas de optimización, batería, actividad, apps y seguridad con confirmación antes de actuar.',
    ],
  },
  en: {
    eyebrow: 'Desktop pet widget for Windows',
    title: 'Feeling too alone with your computer?',
    lead: 'WML X.X.0 is a floating Windows pet that lives above your desktop: it earns points from local signals, unlocks skins, and helps through local AI without reading what you type.',
    petLabel: 'Pets',
    pet: 'Hedgehog and duck',
    pointsLabel: 'Points',
    points: 'Clicks and typing',
    downloadsLabel: 'Downloads',
    versionLabel: 'Version',
    version: 'WML X.X.0',
    emailPlaceholder: 'you@email.com',
    desktopCta: 'Subscribe and download',
    desktopHint: 'Newsletter subscription is required. After that, you will review how the widget works before the download starts.',
    creatorsTitle: 'Creators only: earn money with WML X.X.0',
    creatorsText: 'Create your own skins and sell them in the marketplace. Make money creating art.',
    creatorsCta: 'Create skins',
    subscribeSuccess: 'Subscription confirmed. Review and accept how the widget works to download.',
    subscribeError: 'We could not subscribe you. Please try again.',
    invalidEmail: 'Enter a valid email to download.',
    consentTitle: 'Before downloading',
    consentLead: 'To download WML X.X.0, you must confirm that you understand how the widget works.',
    consentItems: [
      'The pet reacts to local activity signals such as clicks and typing, but it does not read what you type.',
      'It may use battery state, pet state, points, common apps, and some basic security signals.',
      'Local AI is prepared on your computer and does not need an API key or internet once installed.',
      'It can analyze CPU, RAM, disk, battery, and safe processes, run optimization tasks, clean temporary files, free RAM, or focus common apps with confirmation.',
      'It does not send personal files, text typed in other apps, or window contents to the local AI.',
      'Suggestions are limited, appear one at a time, and actions that may affect you require confirmation before running.',
      'It does not replace Microsoft Defender, an EDR, or professional antivirus software.',
    ],
    consentCheckbox: 'I understand and accept the described behavior of WML X.X.0.',
    consentCta: 'Accept and download',
    consentRequired: 'You must accept how the widget works to download.',
    requirementsTitle: 'Recommended requirements',
    requirements: [
      'Windows with an internet connection only to download or repair local AI.',
      '8-16 GB RAM recommended.',
      '15-30 GB free for runtime, model, caches, and traces.',
      'Runs on CPU; a compatible GPU improves latency.',
    ],
    platformTitle: 'Choose your system',
    platformLead: 'After accepting, select the Windows version.',
    windowsLabel: 'Windows',
    linuxLabel: 'Linux',
    linuxUnavailable: 'Coming soon',
    choosePlatform: 'Choose Windows to continue.',
    closePopup: 'Close',
    downloadThanksTitle: 'Thank you so much for downloading.',
    mobileDialogTitle: 'You need a computer',
    mobileDialogText: 'We saved your email, but the download is only available from a Windows computer. Open this page from your PC to continue.',
    mobileTitle: 'Download available on desktop only',
    mobileText: 'Open this page from a Windows computer to download the WML X.X.0 desktop pet widget.',
    backHome: 'Back home',
    checks: [
      'Floating pet that stays visible, discreet, and configurable.',
      'Visual shop for species, colors, and accessories bought with points.',
      'Chat assistant with local AI without internet when installation finishes.',
      'Optimization, battery, activity, apps, and security tasks with confirmation before action.',
    ],
  },
} as const

export const skinTemplateCopy = {
  es: {
    eyebrow: 'Lanzamiento de creadores para WML X.X.0',
    title: 'Crea skins para WML.',
    lead: 'Cada creador puede diseñar su propia skin con el estilo que quiera: sprites, animaciones, personajes, mascotas, atuendos y previsualizaciones. Después solo tendrá que empaquetarla siguiendo la plantilla oficial.',
    downloadCta: 'Descargar plantilla',
    downloadHint: 'Descarga la plantilla oficial para preparar los .pet, .clothes, .json, las previsualizaciones y el zip final del marketplace.',
    desktopOnlyHint: 'La plantilla solo se puede descargar desde un ordenador. Abre esta página en PC o portátil para descargarla.',
    widgetTitle: 'Conectado al widget',
    widgetText: 'Publica tu pack en el marketplace.',
    widgetBody: 'Cuando un pack sea aprobado, los usuarios podrán descargarlo en formato zip e importarlo en la app de escritorio.',
    widgetCta: 'Descargar widget',
    galleryLabel: 'Referencias',
    galleryTitle: 'Cualquier estilo, una estructura común.',
    galleryText: 'El arte es libre: pixel art, ilustración, coleccionable 3D, peluche, dibujo animado o lo que encaje con tu pack. La plantilla solo ordena archivos y datos para que la app pueda leerlo.',
    characterTones: ['Juguete cromado', 'Estilo suave', 'Pack ilustrado', 'Skin pixel art'],
    swatches: ['.pet', '.clothes', '.json', '.zip'],
    backHome: 'Volver al inicio',
    stepsTitle: 'Flujo de creador',
    steps: [
      {
        title: 'Diseña tu pack',
        desc: 'Crea cada sprite y animación con tu propio estilo. Puedes hacer mascotas, atuendos, accesorios o una colección completa.',
      },
      {
        title: 'Sigue la plantilla',
        desc: 'Prepara los archivos .pet, .clothes, .json y las previsualizaciones según la estructura oficial para que el pack sea instalable.',
      },
      {
        title: 'Envía el zip',
        desc: 'Comprime el pack y envíalo desde el formulario oficial. Lo revisaremos y, si está correcto, se subirá al marketplace.',
      },
    ],
    detailsTitle: 'Cómo se organiza',
    details: [
      'Un archivo .pet añade una mascota al pack.',
      'Un archivo .clothes contiene atuendos o ropa.',
      'Los .json describen datos, nombres, previsualizaciones y comportamiento.',
      'El pack final se enviará en formato zip para revisión.',
    ],
    coffeeTitle: 'Apoya el kit de creadores',
    coffeeText: 'El formulario oficial de Buy Me a Coffee está abierto directamente aquí para apoyar el kit de creadores.',
    statusLabel: 'Estado',
    statusValue: 'Plantilla disponible; formulario de envio abierto',
  },
  en: {
    eyebrow: 'Creator drop for WML X.X.0',
    title: 'Create skins for WML.',
    lead: 'Each creator can design their own skin in any style: sprites, animations, characters, pets, outfits, and previews. After that, they only need to package it using the official template.',
    downloadCta: 'Download template',
    downloadHint: 'Download the official template to prepare the .pet, .clothes, .json, previews, and final marketplace zip.',
    desktopOnlyHint: 'The template can only be downloaded from a computer. Open this page on a desktop or laptop to download it.',
    widgetTitle: 'Connected to the widget',
    widgetText: 'Publish your pack in the marketplace.',
    widgetBody: 'Once a pack is approved, users will be able to download it as a zip file and import it into the desktop app.',
    widgetCta: 'Download widget',
    galleryLabel: 'Moodboard',
    galleryTitle: 'Any style, one shared structure.',
    galleryText: 'The art is open: pixel art, illustration, 3D collectible, plush, cartoon, or whatever fits your pack. The template only organizes files and data so the app can read them.',
    characterTones: ['Chrome toy', 'Soft drop', 'Sketch pack', 'Pixel skin'],
    swatches: ['.pet', '.clothes', '.json', '.zip'],
    backHome: 'Back home',
    stepsTitle: 'Creator flow',
    steps: [
      {
        title: 'Design your pack',
        desc: 'Create every sprite and animation in your own style. You can make pets, outfits, accessories, or a full collection.',
      },
      {
        title: 'Follow the template',
        desc: 'Prepare the .pet, .clothes, .json, and preview files using the official structure so the pack can be installed.',
      },
      {
        title: 'Submit the zip',
        desc: 'Compress the pack and send it through the official form. We will review it and, if it is correct, upload it to the marketplace.',
      },
    ],
    detailsTitle: 'How it is organized',
    details: [
      'A .pet file adds a pet to the pack.',
      'A .clothes file contains outfits or clothing.',
      'The .json files describe data, names, previews, and behavior.',
      'The final pack will be submitted as a zip file for review.',
    ],
    coffeeTitle: 'Support the creator kit',
    coffeeText: 'The official Buy Me a Coffee form is open directly here to support the creator kit.',
    statusLabel: 'Status',
    statusValue: 'Template available; submission form open',
  },
} as const

export const heroCopy = {
  es: {
    tag: 'WML X.X.0 / mascota local',
    line1: '¿Solo con',
    line2: 'tu ordenador?',
    line3pre: 'WML',
    line3accent: 'X.X.0',
    line4: 'aparece.',
    desc: 'WML X.X.0 es una mascota flotante para Windows: retro, rara y útil. Reacciona a señales locales, suma puntos, desbloquea skins y ofrece ayuda con IA local sin leer lo que escribes.',
    ctaPrimary: 'Descargar',
    ctaGhost: 'Invítame a un café',
    statParticipants: 'Participantes',
    statExperiments: 'Experimento',
    statOptin: 'Control',
  },
  en: {
    tag: 'WML X.X.0 / local pet',
    line1: 'Alone with',
    line2: 'your computer?',
    line3pre: 'WML',
    line3accent: 'X.X.0',
    line4: 'appears.',
    desc: 'WML X.X.0 is a floating Windows pet: retro, odd, and useful. It reacts to local signals, earns points, unlocks skins, and offers local AI help without reading what you type.',
    ctaPrimary: 'Download',
    ctaGhost: 'Buy me a coffee',
    statParticipants: 'Participants',
    statExperiments: 'Experiment',
    statOptin: 'Control',
  },
} as const

export function getCopy<T extends Record<Locale, unknown>>(copy: T, locale: Locale): T[Locale] {
  return copy[locale]
}
