export const proCopy = {
  es: {
    freePrice: '0 €',
    freeFeatures: [
      'Compañía en el escritorio: mascota flotante, discreta y configurable.',
      'Puntos, skins y accesorios para personalizar tu mascota.',
      'Chat con IA local básica, sin internet después de instalar el modelo.',
      'Sugerencias sobre batería, rendimiento y tareas básicas, con confirmación.',
    ],
    features: [
      'Crea y edita archivos, desde hojas de cálculo hasta proyectos de programación.',
      'Analiza tus archivos y carpetas para trabajar con su contenido.',
      'Abre aplicaciones y usa la web para investigar y avanzar tareas.',
      'Propone cambios y acciones de escritorio para que tú los apruebes.',
      'IA local Pro más capaz, disponible sin conexión tras instalarla.',
      'Modo híbrido con tu API y memoria de acciones realizadas.',
      'Sugerencias Pro según tu actividad y el estado del equipo.',
    ],
    includesFree: 'Todo lo del plan normal, más un asistente con el que puedes trabajar.',
    monthly: '4,99 €/mes', annual: '45,99 €/año',
    annualSaving: 'Ahorra un 23 % con el plan anual.',
    renewal: 'Renovación automática cada mes o cada año, según el plan. Puedes desactivarla desde «Gestionar suscripción», al pie de la página de descarga, y conservar Pro hasta el final del periodo pagado.',
    licenseConnection: 'La IA local funciona sin internet mientras la licencia Pro esté vigente. La licencia se activa online y se comprueba periódicamente. Si no te conectas para recibir la renovación, Pro deja de funcionar al terminar el periodo pagado que figura en la licencia.',
    licensePersonal: 'La licencia Pro es personal y queda vinculada al primer ordenador donde se activa. Una copia usada por otra persona no funcionará en tu equipo. Si tu plan sigue activo, puedes solicitar de nuevo tu propia licencia con el mismo correo, sin volver a pagar.',
    licenseRecovery: 'Tu plan Pro sigue activo. Te hemos enviado una copia de tu licencia al correo indicado para que la descargues e importes sin volver a pagar.',
    checkout: 'Continuar al pago', loading: 'Abriendo Stripe…',
    checkoutError: 'No se pudo abrir el pago Pro. Inténtalo de nuevo más tarde.',
    cancelled: 'El pago no se ha completado. Puedes volver a elegir tu plan.',
    manage: 'Gestionar suscripción',
    receiptIntro: 'Consulta el estado de tu compra y descarga tu licencia Pro aquí.',
    receiptTitle: 'Tu asistente Pro está listo',
    receiptChecking: 'Comprobando el pago y preparando tu widget y tu licencia…',
    receiptReady: 'Gracias por elegir Pro. Tu periodo está confirmado y ya puedes empezar.',
    receiptPending: 'Stripe todavía no ha confirmado el pago. La descarga se habilitará cuando esté pagado.',
    receiptError: 'No hemos podido preparar las descargas. Vuelve a intentarlo. Para gestionar tu suscripción, entra en el portal de Stripe.',
    receiptInactive: 'La suscripción no tiene acceso Pro activo. Puedes revisar el pago y la renovación en Stripe.',
    receiptAuth: 'Abre esta página desde el navegador con el que hiciste el pago. Si has borrado sus cookies, contacta con soporte para recuperar la licencia.',
    retry: 'Volver a comprobar', installer: 'Descargar widget Pro', license: 'Descargar pro-license.json',
    importLicense: 'Abre WML X.X.0 y ve a Ajustes → Importar licencia. Selecciona pro-license.json. La primera activación necesita conexión y vincula la licencia a este ordenador.',
    paidUntil: 'Periodo pagado hasta', back: 'Volver a los planes',
    proConsent: [
      'Pro puede trabajar con los archivos y carpetas que elijas compartir con el asistente.',
      'El modo híbrido es BYOK: usas tu propia clave API. Las peticiones que envíes a un proveedor externo salen de tu equipo y pueden incluir el contenido que compartas.',
      'La memoria híbrida guarda ejemplos de acciones anteriores para reutilizarlos en tareas similares. No es entrenamiento continuo del modelo.',
    ],
  },
  en: {
    freePrice: '€0',
    freeFeatures: [
      'Desktop companionship: a floating, discreet and configurable pet.',
      'Points, skins and accessories to customise your pet.',
      'Basic local AI chat, offline after installing the model.',
      'Battery, performance and basic task suggestions, with confirmation.',
    ],
    features: [
      'Create and edit files, from spreadsheets to coding projects.',
      'Analyse your files and folders to work with their contents.',
      'Open apps and use the web to research and move tasks forward.',
      'Propose file changes and desktop actions for your approval.',
      'More capable local Pro AI, available offline once installed.',
      'Hybrid mode with your API and memory of completed actions.',
      'Pro suggestions based on your activity and your computer.',
    ],
    includesFree: 'Everything in the normal plan, plus an assistant you can work with.',
    monthly: '€4.99/month', annual: '€45.99/year',
    annualSaving: 'Save 23% with the annual plan.',
    renewal: 'Automatic renewal every month or year, depending on your plan. Turn it off via “Manage subscription” at the bottom of the download page and keep Pro until the end of your paid period.',
    licenseConnection: 'Local AI works offline while the Pro license is valid. The license is activated online and checked periodically. If you do not reconnect to receive the renewal, Pro stops working at the end of the paid period shown in the license.',
    licensePersonal: 'Your Pro license is personal and binds to the first computer where it is activated. A copy used by someone else will not work on your computer. If your plan is still active, you can request your own license again with the same email without paying again.',
    licenseRecovery: 'Your Pro plan is still active. We emailed a copy of your license to the address you entered so you can download and import it without paying again.',
    checkout: 'Continue to payment', loading: 'Opening Stripe…',
    checkoutError: 'Pro checkout could not open. Please try again later.',
    cancelled: 'Payment was not completed. You can choose your plan again.',
    manage: 'Manage subscription',
    receiptIntro: 'Check your purchase status and download your Pro license here.',
    receiptTitle: 'Your Pro assistant is ready',
    receiptChecking: 'Checking payment and preparing your widget and license…',
    receiptReady: 'Thank you for choosing Pro. Your paid period is confirmed and you can get started.',
    receiptPending: 'Stripe has not confirmed payment yet. Downloads become available once payment is confirmed.',
    receiptError: 'We could not prepare the downloads. Please retry. You can manage your subscription in the Stripe portal.',
    receiptInactive: 'This subscription does not have active Pro access. Review payment and renewal in Stripe.',
    receiptAuth: 'Open this page in the browser you used to pay. If you cleared its cookies, contact support to recover your license.',
    retry: 'Check again', installer: 'Download Pro widget', license: 'Download pro-license.json',
    importLicense: 'Open WML X.X.0 and go to Settings → Import license. Select pro-license.json. First activation needs a connection and binds the license to this computer.',
    paidUntil: 'Paid period ends', back: 'Back to plans',
    proConsent: [
      'Pro can work with the files and folders you choose to share with the assistant.',
      'Hybrid mode is BYOK: use your own API key. Requests to external providers leave your computer and may include content you choose to share.',
      'Hybrid memory saves examples of previous actions for reuse in similar tasks. It is not continuous model training.',
    ],
  },
} as const
